//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cst_Recete
    {
        public int Rec_Id { get; set; }
        public string Rec_Departman { get; set; }
        public Nullable<int> Rec_Grup { get; set; }
        public string Rec_Anagrup { get; set; }
        public string Rec_Altgrup { get; set; }
        public string Rec_Kodu { get; set; }
        public string Rec_Genelkod { get; set; }
        public string Rec_Ad { get; set; }
        public Nullable<int> Rec_Kisi { get; set; }
        public Nullable<decimal> Rec_Fiyat { get; set; }
        public Nullable<decimal> Rec_Kdv { get; set; }
        public Nullable<decimal> Rec_Net { get; set; }
        public string Rec_Dovizkodu { get; set; }
        public Nullable<decimal> Rec_Dovifiyat { get; set; }
        public string Rec_Urungrup { get; set; }
        public Nullable<bool> Rec_All { get; set; }
        public Nullable<bool> Rec_Ultra { get; set; }
        public Nullable<bool> Rec_HappyHour { get; set; }
        public Nullable<bool> Rec_Pasif { get; set; }
        public Nullable<bool> Rec_FB { get; set; }
        public Nullable<bool> Rec_HB { get; set; }
        public Nullable<bool> Rec_Pdapasif { get; set; }
        public Nullable<bool> Rec_Minibar { get; set; }
        public Nullable<bool> Rec_SiparisCikmasin { get; set; }
        public Nullable<bool> Rec_Miktar_Sor { get; set; }
        public Nullable<bool> Rec_Miktar_Gr { get; set; }
        public Nullable<bool> Rec_Tutar_Sor { get; set; }
        public string Rec_Ust_Recete { get; set; }
        public Nullable<decimal> Rec_Yarim { get; set; }
        public Nullable<decimal> Rec_Birbucuk { get; set; }
        public Nullable<decimal> Rec_Duble { get; set; }
        public Nullable<decimal> Rec_Aksam_Yarim { get; set; }
        public Nullable<decimal> Rec_Aksam_Birbucuk { get; set; }
        public Nullable<decimal> Rec_Aksam_Duble { get; set; }
        public Nullable<decimal> Rec_Paket_Yarim { get; set; }
        public Nullable<decimal> Rec_Paket_Birbucuk { get; set; }
        public Nullable<decimal> Rec_Paket_Duble { get; set; }
        public string Rec_Santral_Minibar { get; set; }
        public Nullable<int> Rec_Sira { get; set; }
        public string Rec_Barkod { get; set; }
        public Nullable<bool> Rec_Terazi { get; set; }
        public Nullable<bool> Rec_SpUygulanmasin { get; set; }
        public Nullable<decimal> Rec_HappyHourFiyat { get; set; }
        public Nullable<decimal> Rec_Aksam_Tam { get; set; }
        public Nullable<decimal> Rec_Paket_Tam { get; set; }
        public string Rec_DetayGrup { get; set; }
        public byte[] Rec_Picture { get; set; }
        public string Rec_Ad_Eng { get; set; }
        public string Rec_Ad_Deu { get; set; }
        public string Rec_Ad_Rus { get; set; }
        public string Rec_Ad_Dig { get; set; }
        public Nullable<int> Rec_YkasaBirim { get; set; }
        public Nullable<decimal> Rec_UretimMiktar { get; set; }
        public string Rec_UretimBirim { get; set; }
        public string Rec_YS_UrunID { get; set; }
        public Nullable<bool> Rec_Update { get; set; }
        public string Rec_Color { get; set; }
        public string Rec_Printer { get; set; }
        public string Rec_AbuyerPR { get; set; }
        public Nullable<bool> Rec_AciklamaAP { get; set; }
        public string Rec_AciklamaGrup { get; set; }
        public string Rec_GetirMenuID { get; set; }
        public string Rec_OptionID { get; set; }
        public Nullable<decimal> Rec_KategoriFiyat1 { get; set; }
        public Nullable<decimal> Rec_KategoriFiyat2 { get; set; }
        public Nullable<decimal> Rec_KategoriFiyat3 { get; set; }
        public Nullable<decimal> Rec_KategoriFiyat4 { get; set; }
        public Nullable<decimal> Rec_KategoriFiyat5 { get; set; }
    }
}
