//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cst_Recete_Satis
    {
        public int Rsat_Id { get; set; }
        public Nullable<int> Rsat_Fisno { get; set; }
        public Nullable<System.DateTime> Rsat_Tarih { get; set; }
        public string Rsat_Departman { get; set; }
        public string Rsat_Recete { get; set; }
        public Nullable<decimal> Rsat_Kdvoran { get; set; }
        public Nullable<decimal> Rsat_Miktar { get; set; }
        public Nullable<decimal> Rsat_Fiyat { get; set; }
        public Nullable<decimal> Rsat_Ind { get; set; }
        public Nullable<decimal> Rsat_Net { get; set; }
        public Nullable<decimal> Rsat_Kdv { get; set; }
        public Nullable<decimal> Rsat_Tutar { get; set; }
        public Nullable<decimal> Rsat_Maliyet { get; set; }
        public string Rsat_Dovizkodu { get; set; }
        public Nullable<decimal> Rsat_Doviztutar { get; set; }
        public string Rsat_Satistip { get; set; }
        public string Rsat_Odenmez { get; set; }
        public string Rsat_Odano { get; set; }
        public Nullable<int> Rsat_Folio { get; set; }
        public string Rsat_Ba { get; set; }
        public string Rsat_Kapatma { get; set; }
        public string Rsat_Adisyon { get; set; }
        public Nullable<int> Rsat_Aktiffisno { get; set; }
        public string Rsat_Masa { get; set; }
        public string Rsat_Garson { get; set; }
        public Nullable<int> Rsat_Kisi { get; set; }
        public Nullable<System.TimeSpan> Rsat_Acilis { get; set; }
        public Nullable<System.TimeSpan> Rsat_Kapanis { get; set; }
        public string Rsat_Durum { get; set; }
        public string Rsat_Cari { get; set; }
        public Nullable<int> Rsat_Split { get; set; }
        public string Rsat_Aciklama { get; set; }
        public Nullable<bool> Rsat_SiparisPr { get; set; }
        public Nullable<bool> Rsat_AdisyonPr { get; set; }
        public string Rsat_Paketci { get; set; }
        public string Rsat_Emiktar { get; set; }
        public Nullable<bool> Rsat_AdisPr { get; set; }
        public string Rsat_Garson2 { get; set; }
        public Nullable<int> Rsat_AdisPrSayac { get; set; }
        public string Rsat_Uye_Kart_Turu { get; set; }
        public Nullable<bool> Rsat_Satir_Iptal { get; set; }
        public string Rsat_Pansiyon { get; set; }
        public Nullable<bool> Rsat_Happy_Hour { get; set; }
        public string Rsat_MusTipi { get; set; }
        public Nullable<int> Rsat_Uye_Id { get; set; }
        public string Rsat_Uye_Ad { get; set; }
        public string Rsat_Indkodu { get; set; }
        public Nullable<decimal> Rsat_Indoran { get; set; }
        public string Rsat_Onbdep { get; set; }
        public Nullable<int> Rsat_Indsatirid { get; set; }
        public Nullable<System.TimeSpan> Rsat_Satissaat { get; set; }
        public Nullable<decimal> Rsat_Dovizkur { get; set; }
        public Nullable<System.TimeSpan> Rsat_Satir_Iptalsaat { get; set; }
        public Nullable<int> Rsat_Indsatirid2 { get; set; }
        public string Rsat_Not { get; set; }
        public string Rsat_Kartno { get; set; }
        public Nullable<bool> Rsat_Pda { get; set; }
        public Nullable<bool> Rsat_Mars { get; set; }
        public Nullable<bool> Rsat_Yapildi { get; set; }
        public string Rsat_Splitad { get; set; }
        public Nullable<bool> Rsat_Hesap_Kilit { get; set; }
        public Nullable<bool> Rsat_Zayi { get; set; }
        public Nullable<bool> Rsat_Ikram { get; set; }
        public Nullable<bool> Rsat_AbuyerPr { get; set; }
        public Nullable<bool> Rsat_Yapma { get; set; }
        public string Rsat_ZayiNeden { get; set; }
        public string Rsat_IkramNeden { get; set; }
        public string Rsat_Sube { get; set; }
        public string Rsat_SubeDurum { get; set; }
        public string Rsat_OzelMasaAdi { get; set; }
        public Nullable<System.DateTime> Rsat_SistemDate { get; set; }
        public Nullable<int> Rsat_Kart_ID { get; set; }
        public Nullable<bool> Rsat_AdisyonTR { get; set; }
        public Nullable<bool> Rsat_AbuyerPr2 { get; set; }
        public Nullable<bool> Rsat_AbuyerPr3 { get; set; }
        public Nullable<bool> Rsat_AbuyerPr4 { get; set; }
        public Nullable<int> Rsat_Ingenico_Status { get; set; }
        public Nullable<bool> Rsat_IWERep { get; set; }
        public string Rsat_SiraAciklama { get; set; }
        public string Rsat_YSDurum { get; set; }
        public string Rsat_YSOrderID { get; set; }
        public Nullable<int> Rsat_UrunTahsilat { get; set; }
        public string Rsat_YerliYabanci { get; set; }
        public string Rsat_PR { get; set; }
        public Nullable<int> Rsat_UrunBazliHspDokum { get; set; }
        public string Rsat_Joker { get; set; }
        public Nullable<int> Rsat_UrunBazliHspAdet { get; set; }
        public Nullable<int> Rsat_RecAP { get; set; }
        public string Rsat_GetirOrderID { get; set; }
        public Nullable<int> Rsat_GetirDurum { get; set; }
        public string Rsat_EntegreId { get; set; }
        public Nullable<int> Rsat_EntegreDurumKod { get; set; }
        public string Rsat_EntegreAd { get; set; }
        public Nullable<decimal> Rsat_EntegreToplamFiyat { get; set; }
    }
}
