//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class entegreMenu
    {
        public int id { get; set; }
        public Nullable<int> tip { get; set; }
        public string entegreId { get; set; }
        public string entegreAd { get; set; }
        public string entegreMenuMasterId { get; set; }
        public string entegreAciklama { get; set; }
        public Nullable<decimal> urunSabitFiyat { get; set; }
        public string recId { get; set; }
        public string recAd { get; set; }
        public Nullable<decimal> recFiyat { get; set; }
        public Nullable<bool> aktif { get; set; }
        public Nullable<int> masterId { get; set; }
        public string recDep { get; set; }
        public string entegreJson { get; set; }
    }
}
