//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class entegreSiparisUrunler
    {
        public int id { get; set; }
        public Nullable<int> tip { get; set; }
        public string siparisId { get; set; }
        public string siparisIdDiger { get; set; }
        public string entegreMenuId { get; set; }
        public string entegreMenuAd { get; set; }
        public string entegreMenuMasterId { get; set; }
        public string recId { get; set; }
        public string recAd { get; set; }
        public Nullable<decimal> recFiyat { get; set; }
        public string recDep { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<bool> ismenu { get; set; }
        public Nullable<decimal> urunSabitFiyat { get; set; }
        public Nullable<int> adet { get; set; }
        public string packageItemId { get; set; }
    }
}
