//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class entegreSiparis
    {
        public int id { get; set; }
        public Nullable<int> tip { get; set; }
        public string siparisId { get; set; }
        public string siparisIdDiger { get; set; }
        public string cariId { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public Nullable<decimal> siparisTutar { get; set; }
        public string kuryeTip { get; set; }
        public Nullable<int> durumKod { get; set; }
        public string entegreDurum { get; set; }
        public string durumText { get; set; }
        public string odemeTip { get; set; }
        public string adres { get; set; }
        public string tel { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string kat { get; set; }
        public string daireno { get; set; }
        public string apartmanno { get; set; }
        public string mahalle { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string mail { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<System.DateTime> guncellemeTarih { get; set; }
        public string siparisNot { get; set; }
        public Nullable<int> fisno { get; set; }
        public string recDep { get; set; }
    }
}
