//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class entegreAyarlar
    {
        public int id { get; set; }
        public Nullable<bool> getirDurum { get; set; }
        public Nullable<bool> trendyolDurum { get; set; }
        public string getirRestaurantSecretKey { get; set; }
        public string getirAppSecretKey { get; set; }
        public Nullable<int> trendyolSupplierId { get; set; }
        public Nullable<int> trendyolStoreId { get; set; }
        public string trendyolApiKey { get; set; }
        public string trendyolApiSecret { get; set; }
        public string trendyolApiLink { get; set; }
        public Nullable<bool> trendyolApiTest { get; set; }
        public Nullable<int> timerSn { get; set; }
        public string eslesmeyenUrunId { get; set; }
        public string eslesmeyenUrunAd { get; set; }
        public Nullable<decimal> eslesmeyenUrunFiyat { get; set; }
        public string recDep { get; set; }
        public string timerCount { get; set; }
    }
}
