//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class entegreJson
    {
        public int id { get; set; }
        public string json { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> tip { get; set; }
        public string jsonTip { get; set; }
        public string recDep { get; set; }
    }
}
