//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class entegreOdemeTip
    {
        public int id { get; set; }
        public Nullable<int> tip { get; set; }
        public string entegreOdemeType { get; set; }
        public string entegreOdemeKod { get; set; }
        public string entegreOdemeAd { get; set; }
        public string recOdemeKod { get; set; }
        public string recOdemeAd { get; set; }
        public string recDep { get; set; }
    }
}
