//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RmosMerkez21Entities : DbContext
    {
        public RmosMerkez21Entities()
                 : base("name=RmosMerkez21Entities")
        {
        }

        public RmosMerkez21Entities(string server, string veritab, string user, string sifre)
                     : base("metadata=res://*;"
                 + "provider=System.Data.SqlClient;"
                 + "provider connection string=';"
               + "Data Source=" + server + ";"
               + "Initial Catalog=" + veritab + ";"
               + "Persist Security Info=True;"
               + "User ID=" + user + ";Password=" + sifre + ";"
               + "MultipleActiveResultSets=True';")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Stok_Kodlar> Stok_Kodlar { get; set; }
        public virtual DbSet<Cst_Recete> Cst_Recete { get; set; }
        public virtual DbSet<Cst_Recete_Satis> Cst_Recete_Satis { get; set; }
        public virtual DbSet<Pos_Cari> Pos_Cari { get; set; }
        public virtual DbSet<entegreAyarlar> entegreAyarlar { get; set; }
        public virtual DbSet<entegreJson> entegreJson { get; set; }
        public virtual DbSet<entegreOdemeTip> entegreOdemeTip { get; set; }
        public virtual DbSet<entegreSiparis> entegreSiparis { get; set; }
        public virtual DbSet<entegreSiparisUrunler> entegreSiparisUrunler { get; set; }
        public virtual DbSet<entegreMenu> entegreMenu { get; set; }
    }
}
