//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pos_Cari
    {
        public int Cari_Id { get; set; }
        public string Cari_Kod { get; set; }
        public string Cari_Ad { get; set; }
        public string Cari_Soyad { get; set; }
        public string Cari_Tel { get; set; }
        public string Cari_Adres1 { get; set; }
        public string Cari_Adres2 { get; set; }
        public string Cari_Adres3 { get; set; }
        public string Cari_Funvan { get; set; }
        public string Cari_Fadres1 { get; set; }
        public string Cari_Fadres2 { get; set; }
        public string Cari_Vergidarie { get; set; }
        public string Cari_Vergino { get; set; }
        public string Cari_Mail { get; set; }
        public string Cari_Kart { get; set; }
        public string Cari_Tel2 { get; set; }
        public string Cari_Email { get; set; }
        public string Cari_Tip { get; set; }
        public Nullable<bool> Cari_Limit { get; set; }
        public Nullable<decimal> Cari_LimitTutar { get; set; }
        public string Cari_Il { get; set; }
        public string Cari_Ilce { get; set; }
        public string Cari_Mahalle { get; set; }
        public string Cari_MuhasebeKodu { get; set; }
        public Nullable<bool> Cari_Aktif { get; set; }
        public string Cari_YS_AddressId { get; set; }
        public string Cari_YS_CustomerID { get; set; }
        public string Cari_Funvan2 { get; set; }
        public Nullable<System.DateTime> Cari_DogumTar { get; set; }
        public string Cari_Getir_ID { get; set; }
        public string Cari_Getir_AddressId { get; set; }
        public Nullable<int> Cari_TrendyolId { get; set; }
    }
}
