//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stok_Kodlar
    {
        public int Kodlar_Id { get; set; }
        public string Kodlar_Kod { get; set; }
        public string Kodlar_Ad { get; set; }
        public string Kodlar_Sinif { get; set; }
        public string Kodlar_Anagrup { get; set; }
        public string Kodlar_Aragrup { get; set; }
        public string Kodlar_Muhkodu { get; set; }
        public Nullable<bool> Kodlar_Icki { get; set; }
        public Nullable<bool> Kodlar_Icki2 { get; set; }
        public Nullable<bool> Kodlar_Tevkifat { get; set; }
        public Nullable<decimal> Kodlar_Tevkifatoran { get; set; }
        public Nullable<decimal> Kodlar_Tevkifattutar { get; set; }
        public Nullable<decimal> Kodlar_Carpan { get; set; }
        public Nullable<bool> Kodlar_Anadepo { get; set; }
        public string Kodlar_YID { get; set; }
        public string Kodlar_Sirket { get; set; }
        public string Kodlar_Butcekodu { get; set; }
        public string Kodlar_Masraf { get; set; }
        public Nullable<bool> Kodlar_Satis { get; set; }
        public Nullable<int> Kodlar_Sorgu { get; set; }
        public string Kodlar_Satishesap { get; set; }
        public Nullable<int> Kodlar_Pesin { get; set; }
        public string Kodlar_Hasar { get; set; }
        public Nullable<bool> Kodlar_Siparis { get; set; }
        public Nullable<bool> Kodlar_Adisyon { get; set; }
        public Nullable<bool> Kodlar_Fatura { get; set; }
        public Nullable<decimal> Kodlar_Kdv { get; set; }
        public Nullable<bool> Kodlar_Kisi { get; set; }
        public Nullable<bool> Kodlar_Garson { get; set; }
        public Nullable<bool> Kodlar_IlkSiparis { get; set; }
        public Nullable<bool> Kodlar_Aktif_Kur { get; set; }
        public string Kodlar_Anadepkodu { get; set; }
        public string Kodlar_Sube { get; set; }
        public string Kodlar_Altgrup { get; set; }
        public Nullable<bool> Kodlar_Pda_Satis { get; set; }
        public Nullable<bool> Kodlar_Hesap_Adisyon { get; set; }
        public Nullable<bool> Kodlar_Minibar { get; set; }
        public Nullable<bool> Kodlar_Onb_Atmasin { get; set; }
        public Nullable<bool> Kodlar_Kuver_Sat { get; set; }
        public string Kodlar_Kuver_Recete { get; set; }
        public Nullable<bool> Kodlar_ServisPayi { get; set; }
        public string Kodlar_Servis_Recete { get; set; }
        public Nullable<decimal> Kodlar_Servis_Yuzde { get; set; }
        public Nullable<bool> Kodlar_Kdv_Aktif { get; set; }
        public Nullable<int> Kodlar_Sira { get; set; }
        public Nullable<bool> Kodlar_Android { get; set; }
        public string Kodlar_Size { get; set; }
        public string Kodlar_Font { get; set; }
        public string Kodlar_Backcolor { get; set; }
        public Nullable<bool> Kodlar_Mars { get; set; }
        public Nullable<bool> Kodlar_Kisisorma_Pda { get; set; }
        public Nullable<bool> Kodlar_Pr_Posta { get; set; }
        public Nullable<bool> Kodlar_YazSipNedSor { get; set; }
        public Nullable<bool> Kodlar_OnbNakit_Atmasin { get; set; }
        public Nullable<bool> Kodlar_OnbKK_Atmasin { get; set; }
        public string Kodlar_PosSubeKod { get; set; }
        public Nullable<bool> Kodlar_RecBarSis { get; set; }
        public Nullable<bool> Kodlar_GunCstEtkilenmesin { get; set; }
        public Nullable<bool> Kodlar_AndPos_NFC { get; set; }
        public Nullable<bool> Kodlar_PaketFiyat { get; set; }
        public string Kodlar_NFCKapatma { get; set; }
        public string Kodlar_YS_User { get; set; }
        public string Kodlar_YS_Pass { get; set; }
        public Nullable<bool> Kodlar_YS_Aktif { get; set; }
        public Nullable<bool> Kodlar_MenuAktif { get; set; }
        public Nullable<System.TimeSpan> Kodlar_Menu_BasSaat { get; set; }
        public Nullable<System.TimeSpan> Kodlar_Menu_BitSaat { get; set; }
        public Nullable<int> Kodlar_YKasaid { get; set; }
        public Nullable<bool> Kodlar_Ingenico { get; set; }
        public string Kodlar_IngenicoKDV { get; set; }
        public Nullable<int> Kodlar_IngenicoCon { get; set; }
        public string Kodlar_Ingenico_IP { get; set; }
        public Nullable<int> Kodlar_Ingenico_Port { get; set; }
        public Nullable<bool> Kodlar_Ingenico_IWE { get; set; }
        public string Kodlar_Satishesap8 { get; set; }
        public string Kodlar_Satishesap18 { get; set; }
        public Nullable<bool> Kodlar_GGAktif { get; set; }
        public Nullable<bool> Kodlar_GGFiyat { get; set; }
        public Nullable<bool> Kodlar_YerliYabanci { get; set; }
        public Nullable<bool> Kodlar_PrinterApi { get; set; }
        public Nullable<bool> Kodlar_PRSor { get; set; }
        public Nullable<bool> Kodlar_UrunPrint { get; set; }
        public Nullable<bool> Kodlar_Andro_Signature { get; set; }
        public string Kodlar_YSMac { get; set; }
        public Nullable<bool> Kodlar_SmsAktif { get; set; }
        public string Kodlar_SmsBaslik { get; set; }
        public string Kodlar_SmsKadi { get; set; }
        public string Kodlar_SmsSifre { get; set; }
        public string Kodlar_Getir_appSecretKey { get; set; }
        public string Kodlar_Getir_restaurantSecretKey { get; set; }
        public Nullable<decimal> Kodlar_IngenicoKDVOran { get; set; }
        public Nullable<bool> Kodlar_Getir_AP { get; set; }
        public Nullable<bool> Kodlar_IWE_hspDokum { get; set; }
        public Nullable<int> Kodlar_KategoriFiyatTur { get; set; }
        public string Kodlar_Satishesap0 { get; set; }
    }
}
