USE [Back2019]
GO

/****** Object:  UserDefinedTableType [dbo].[Cst_Recete_Satis_Type]    Script Date: 15.05.2024 17:05:52 ******/
CREATE TYPE [dbo].[Cst_Recete_Satis_Type] AS TABLE(
	[Rsat_Fisno] [int] NULL,
	[Rsat_Tarih] [datetime] NULL,
	[Rsat_Departman] [nvarchar](10) NULL,
	[Rsat_Recete] [nvarchar](30) NULL,
	[Rsat_Kdvoran] [decimal](18, 2) NULL,
	[Rsat_Miktar] [decimal](18, 2) NULL,
	[Rsat_Fiyat] [decimal](18, 2) NULL,
	[Rsat_Ind] [decimal](18, 2) NULL,
	[Rsat_Net] [decimal](18, 2) NULL,
	[Rsat_Kdv] [decimal](18, 2) NULL,
	[Rsat_Tutar] [decimal](18, 2) NULL,
	[Rsat_Maliyet] [decimal](18, 4) NULL,
	[Rsat_Dovizkodu] [nvarchar](10) NULL,
	[Rsat_Doviztutar] [decimal](18, 2) NULL,
	[Rsat_Satistip] [nvarchar](2) NULL,
	[Rsat_Odenmez] [nvarchar](100) NULL,
	[Rsat_Odano] [nvarchar](100) NULL,
	[Rsat_Folio] [int] NULL,
	[Rsat_Ba] [nvarchar](1) NULL,
	[Rsat_Kapatma] [nvarchar](10) NULL,
	[Rsat_Adisyon] [nvarchar](50) NULL,
	[Rsat_Aktiffisno] [int] NULL,
	[Rsat_Masa] [nvarchar](50) NULL,
	[Rsat_Garson] [nvarchar](50) NULL,
	[Rsat_Kisi] [int] NULL,
	[Rsat_Acilis] [time](7) NULL,
	[Rsat_Kapanis] [time](7) NULL,
	[Rsat_Durum] [nvarchar](1) NULL,
	[Rsat_Cari] [nvarchar](50) NULL,
	[Rsat_Split] [int] NULL,
	[Rsat_Aciklama] [nvarchar](100) NULL,
	[Rsat_SiparisPr] [bit] NULL,
	[Rsat_AdisyonPr] [bit] NULL,
	[Rsat_Paketci] [nvarchar](50) NULL,
	[Rsat_Emiktar] [nvarchar](50) NULL,
	[Rsat_AdisPr] [bit] NULL,
	[Rsat_Garson2] [nvarchar](50) NULL,
	[Rsat_AdisPrSayac] [int] NULL,
	[Rsat_Uye_Kart_Turu] [nvarchar](20) NULL,
	[Rsat_Satir_Iptal] [bit] NULL,
	[Rsat_Pansiyon] [nvarchar](20) NULL,
	[Rsat_Happy_Hour] [bit] NULL,
	[Rsat_MusTipi] [nvarchar](1) NULL,
	[Rsat_Uye_Id] [int] NULL,
	[Rsat_Uye_Ad] [nvarchar](100) NULL,
	[Rsat_Indkodu] [nvarchar](50) NULL,
	[Rsat_Indoran] [decimal](18, 2) NULL,
	[Rsat_Onbdep] [nvarchar](20) NULL,
	[Rsat_Indsatirid] [int] NULL,
	[Rsat_Satissaat] [time](7) NULL,
	[Rsat_Dovizkur] [decimal](18, 4) NULL,
	[Rsat_Satir_Iptalsaat] [time](7) NULL,
	[Rsat_Indsatirid2] [int] NULL,
	[Rsat_Not] [nvarchar](1000) NULL,
	[Rsat_Kartno] [nvarchar](50) NULL,
	[Rsat_Pda] [bit] NULL,
	[Rsat_Mars] [bit] NULL,
	[Rsat_Yapildi] [bit] NULL,
	[Rsat_Splitad] [nvarchar](50) NULL,
	[Rsat_Hesap_Kilit] [bit] NULL,
	[Rsat_Zayi] [bit] NULL,
	[Rsat_Ikram] [bit] NULL,
	[Rsat_AbuyerPr] [bit] NULL,
	[Rsat_Yapma] [bit] NULL,
	[Rsat_ZayiNeden] [nvarchar](255) NULL,
	[Rsat_IkramNeden] [nvarchar](255) NULL,
	[Rsat_Sube] [nvarchar](50) NULL,
	[Rsat_SubeDurum] [nvarchar](50) NULL,
	[Rsat_OzelMasaAdi] [nvarchar](50) NULL,
	[Rsat_SistemDate] [datetime] NULL,
	[Rsat_Kart_ID] [int] NULL,
	[Rsat_AdisyonTR] [bit] NULL,
	[Rsat_AbuyerPr2] [bit] NULL,
	[Rsat_AbuyerPr3] [bit] NULL,
	[Rsat_AbuyerPr4] [bit] NULL,
	[Rsat_Ingenico_Status] [int] NULL,
	[Rsat_IWERep] [bit] NULL,
	[Rsat_SiraAciklama] [nvarchar](50) NULL,
	[Rsat_YSDurum] [nvarchar](100) NULL,
	[Rsat_YSOrderID] [nvarchar](100) NULL,
	[Rsat_UrunTahsilat] [nvarchar](100) NULL,
	[Rsat_YerliYabanci] [nvarchar](100) NULL,
	[Rsat_PR] [nvarchar](100) NULL,
	[Rsat_UrunBazliHspDokum] [nvarchar](100) NULL
)
GO


