USE [Back2019]
GO

/****** Object:  UserDefinedTableType [dbo].[Cst_Recete_Type]    Script Date: 15.05.2024 17:06:26 ******/
CREATE TYPE [dbo].[Cst_Recete_Type] AS TABLE(
	[Rec_Departman] [nvarchar](100) NULL,
	[Rec_Grup] [int] NULL,
	[Rec_Anagrup] [nvarchar](10) NULL,
	[Rec_Altgrup] [nvarchar](10) NULL,
	[Rec_Kodu] [nvarchar](10) NULL,
	[Rec_Genelkod] [nvarchar](30) NULL,
	[Rec_Ad] [nvarchar](50) NULL,
	[Rec_Kisi] [int] NULL,
	[Rec_Fiyat] [decimal](18, 2) NULL,
	[Rec_Kdv] [decimal](18, 2) NULL,
	[Rec_Net] [decimal](18, 2) NULL,
	[Rec_Dovizkodu] [nvarchar](10) NOT NULL,
	[Rec_Dovifiyat] [decimal](18, 2) NULL,
	[Rec_Urungrup] [nvarchar](10) NULL,
	[Rec_All] [bit] NULL,
	[Rec_Ultra] [bit] NULL,
	[Rec_HappyHour] [bit] NULL,
	[Rec_Pasif] [bit] NULL,
	[Rec_FB] [bit] NULL,
	[Rec_HB] [bit] NULL,
	[Rec_Pdapasif] [bit] NULL,
	[Rec_Minibar] [bit] NULL,
	[Rec_SiparisCikmasin] [bit] NULL,
	[Rec_Miktar_Sor] [bit] NULL,
	[Rec_Miktar_Gr] [bit] NULL,
	[Rec_Tutar_Sor] [bit] NULL,
	[Rec_Ust_Recete] [nvarchar](30) NULL,
	[Rec_Yarim] [decimal](18, 2) NULL,
	[Rec_Birbucuk] [decimal](18, 2) NULL,
	[Rec_Duble] [decimal](18, 2) NULL,
	[Rec_Aksam_Yarim] [decimal](18, 2) NULL,
	[Rec_Aksam_Birbucuk] [decimal](18, 2) NULL,
	[Rec_Aksam_Duble] [decimal](18, 2) NULL,
	[Rec_Paket_Yarim] [decimal](18, 2) NULL,
	[Rec_Paket_Birbucuk] [decimal](18, 2) NULL,
	[Rec_Paket_Duble] [decimal](18, 2) NULL,
	[Rec_Santral_Minibar] [nvarchar](50) NULL,
	[Rec_Sira] [int] NULL,
	[Rec_Barkod] [nvarchar](150) NULL,
	[Rec_Terazi] [bit] NULL,
	[Rec_SpUygulanmasin] [bit] NULL,
	[Rec_HappyHourFiyat] [decimal](18, 2) NULL,
	[Rec_Aksam_Tam] [decimal](18, 2) NULL,
	[Rec_Paket_Tam] [decimal](18, 2) NULL,
	[Rec_DetayGrup] [nvarchar](50) NULL,
	[Rec_Picture] [varbinary](1) NULL,
	[Rec_Ad_Eng] [nvarchar](50) NULL,
	[Rec_Ad_Deu] [nvarchar](50) NULL,
	[Rec_Ad_Rus] [nvarchar](50) NULL,
	[Rec_Ad_Dig] [nvarchar](50) NULL,
	[Rec_YkasaBirim] [int] NULL,
	[Rec_UretimMiktar] [decimal](18, 2) NULL,
	[Rec_UretimBirim] [nvarchar](50) NULL,
	[Rec_YS_UrunID] [nvarchar](100) NULL,
	[Rec_Update] [bit] NULL
)
GO


