//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Class {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_tr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_tr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pos.Class.lang_tr", typeof(lang_tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acik Çekler Sayısı ve Tutarı.
        /// </summary>
        internal static string Acik_Çekler_Sayısı_ve_Tutarı {
            get {
                return ResourceManager.GetString("Acik Çekler Sayısı ve Tutarı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açık Masa Kişi Sayısı :.
        /// </summary>
        internal static string Açık_Masa_Kişi_Sayısı__ {
            get {
                return ResourceManager.GetString("Açık Masa Kişi Sayısı :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açık Masayı Masayı Geri Alamazsınız....
        /// </summary>
        internal static string Açık_Masayı_Masayı_Geri_Alamazsınız___ {
            get {
                return ResourceManager.GetString("Açık Masayı Masayı Geri Alamazsınız...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açmıştır.Başkası Satış Yapamaz...!!!.
        /// </summary>
        internal static string Açmıştır_Başkası_Satış_Yapamaz______ {
            get {
                return ResourceManager.GetString("Açmıştır.Başkası Satış Yapamaz...!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Bos Gecilemez....
        /// </summary>
        internal static string Ad_Bos_Gecilemez___ {
            get {
                return ResourceManager.GetString("Ad Bos Gecilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Boş Geçilemez....
        /// </summary>
        internal static string Ad_Boş_Geçilemez___ {
            get {
                return ResourceManager.GetString("Ad Boş Geçilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad ve Soyad Boş Geçilemez....
        /// </summary>
        internal static string Ad_ve_Soyad_Boş_Geçilemez___ {
            get {
                return ResourceManager.GetString("Ad ve Soyad Boş Geçilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adisyon Dökülecek... Devam Etmek İstiyor Musunuz ?.
        /// </summary>
        internal static string Adisyon_Dökülecek____Devam_Etmek_İstiyor_Musunuz__ {
            get {
                return ResourceManager.GetString("Adisyon Dökülecek... Devam Etmek İstiyor Musunuz ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adisyon Dökülecek... Devam Etmek İstiyor Musunuz...?.
        /// </summary>
        internal static string Adisyon_Dökülecek____Devam_Etmek_İstiyor_Musunuz____ {
            get {
                return ResourceManager.GetString("Adisyon Dökülecek... Devam Etmek İstiyor Musunuz...?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adisyon için Bir Printer Seçimi Yapılmamış....
        /// </summary>
        internal static string Adisyon_için_Bir_Printer_Seçimi_Yapılmamış___ {
            get {
                return ResourceManager.GetString("Adisyon için Bir Printer Seçimi Yapılmamış...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktarim Bitmistir \r\n Kod Sinifları \r\n 91:Odeme Sekilleri \r\n 92:Departman Kısımları \r\n 93:Bankalar \r\n 94:Yemek Cekleri.
        /// </summary>
        internal static string Aktarim_Bitmistir__r_n_Kod_Sinifları__r_n_91_Odeme_Sekilleri__r_n_92_Departman_Kısımları__r_n_93_Bankalar__r_n_94_Yemek_Cekleri {
            get {
                return ResourceManager.GetString("Aktarim Bitmistir \\r\\n Kod Sinifları \\r\\n 91:Odeme Sekilleri \\r\\n 92:Departman Kı" +
                        "sımları \\r\\n 93:Bankalar \\r\\n 94:Yemek Cekleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktarım Yapmadan Once Eslestirme Yapılması Gerekir.
        /// </summary>
        internal static string Aktarım_Yapmadan_Once_Eslestirme_Yapılması_Gerekir {
            get {
                return ResourceManager.GetString("Aktarım Yapmadan Once Eslestirme Yapılması Gerekir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alacak Satırı üzerinde İşlem Yapamazsınız....
        /// </summary>
        internal static string Alacak_Satırı_üzerinde_İşlem_Yapamazsınız___ {
            get {
                return ResourceManager.GetString("Alacak Satırı üzerinde İşlem Yapamazsınız...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Grup Boş Geçilemez....
        /// </summary>
        internal static string Ana_Grup_Boş_Geçilemez___ {
            get {
                return ResourceManager.GetString("Ana Grup Boş Geçilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlarınızda Sorun Var....
        /// </summary>
        internal static string Ayarlarınızda_Sorun_Var___ {
            get {
                return ResourceManager.GetString("Ayarlarınızda Sorun Var...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı Kart Numarası Başka Kullanıcıda Tanımlı. Kart Numarasını Değiştiriniz....
        /// </summary>
        internal static string Aynı_Kart_Numarası_Başka_Kullanıcıda_Tanımlı__Kart_Numarasını_Değiştiriniz___ {
            get {
                return ResourceManager.GetString("Aynı Kart Numarası Başka Kullanıcıda Tanımlı. Kart Numarasını Değiştiriniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakiye Yüklemek için Ödeme Departmanını Seçiniz....
        /// </summary>
        internal static string Bakiye_Yüklemek_için_Ödeme_Departmanını_Seçiniz___ {
            get {
                return ResourceManager.GetString("Bakiye Yüklemek için Ödeme Departmanını Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakiye Yüklenmiştir....
        /// </summary>
        internal static string Bakiye_Yüklenmiştir___ {
            get {
                return ResourceManager.GetString("Bakiye Yüklenmiştir...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıc Bitiş Değerleri Sayısal Olmalıdır...!!!.
        /// </summary>
        internal static string Başlangıc_Bitiş_Değerleri_Sayısal_Olmalıdır______ {
            get {
                return ResourceManager.GetString("Başlangıc Bitiş Değerleri Sayısal Olmalıdır...!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baslangıc ve Bitis Değerlerini Giriniz....
        /// </summary>
        internal static string Baslangıc_ve_Bitis_Değerlerini_Giriniz___ {
            get {
                return ResourceManager.GetString("Baslangıc ve Bitis Değerlerini Giriniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgilendirme.
        /// </summary>
        internal static string Bilgilendirme {
            get {
                return ResourceManager.GetString("Bilgilendirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boş Paket Masanız Bulunmamaktadır..
        /// </summary>
        internal static string Boş_Paket_Masanız_Bulunmamaktadır_ {
            get {
                return ResourceManager.GetString("Boş Paket Masanız Bulunmamaktadır.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu Departmana Ait Yazıcı Ayarlarını Kontrol Ediniz....
        /// </summary>
        internal static string Bu_Departmana_Ait_Yazıcı_Ayarlarını_Kontrol_Ediniz___ {
            get {
                return ResourceManager.GetString("Bu Departmana Ait Yazıcı Ayarlarını Kontrol Ediniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu isimde zaten bir rapor var....
        /// </summary>
        internal static string Bu_isimde_zaten_bir_rapor_var___ {
            get {
                return ResourceManager.GetString("Bu isimde zaten bir rapor var...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu İşlemi Yapmaya Yetkiniz Yoktur..
        /// </summary>
        internal static string Bu_İşlemi_Yapmaya_Yetkiniz_Yoktur_ {
            get {
                return ResourceManager.GetString("Bu İşlemi Yapmaya Yetkiniz Yoktur.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari hareket Görmüş Silinemez!.
        /// </summary>
        internal static string Cari_hareket_Görmüş_Silinemez_ {
            get {
                return ResourceManager.GetString("Cari hareket Görmüş Silinemez!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Kodu Boş Geçilemez....
        /// </summary>
        internal static string Cari_Kodu_Boş_Geçilemez___ {
            get {
                return ResourceManager.GetString("Cari Kodu Boş Geçilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Kodu Boş Geçilemez...\nSistem Yeni Kod Versin mi?.
        /// </summary>
        internal static string Cari_Kodu_Boş_Geçilemez____nSistem_Yeni_Kod_Versin_mi_ {
            get {
                return ResourceManager.GetString("Cari Kodu Boş Geçilemez...\\nSistem Yeni Kod Versin mi?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Kodu Giriniz....
        /// </summary>
        internal static string Cari_Kodu_Giriniz___ {
            get {
                return ResourceManager.GetString("Cari Kodu Giriniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari kodu tanımlı değil..
        /// </summary>
        internal static string Cari_kodu_tanımlı_değil_ {
            get {
                return ResourceManager.GetString("Cari kodu tanımlı değil.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departman Bos Geçilemez....
        /// </summary>
        internal static string Departman_Bos_Geçilemez___ {
            get {
                return ResourceManager.GetString("Departman Bos Geçilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departman Parametreleri Yüklenemedi....
        /// </summary>
        internal static string Departman_Parametreleri_Yüklenemedi___ {
            get {
                return ResourceManager.GetString("Departman Parametreleri Yüklenemedi...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devam etmek İstiyor musunuz ? .
        /// </summary>
        internal static string Devam_etmek_İstiyor_musunuz__ {
            get {
                return ResourceManager.GetString("Devam etmek İstiyor musunuz ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devam Etmek İstiyor Musunuz...?.
        /// </summary>
        internal static string Devam_Etmek_İstiyor_Musunuz____ {
            get {
                return ResourceManager.GetString("Devam Etmek İstiyor Musunuz...?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dizany Yüklenemedi....
        /// </summary>
        internal static string Dizany_Yüklenemedi___ {
            get {
                return ResourceManager.GetString("Dizany Yüklenemedi...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzeltilecek Kaydı Seçiniz....
        /// </summary>
        internal static string Düzeltilecek_Kaydı_Seçiniz___ {
            get {
                return ResourceManager.GetString("Düzeltilecek Kaydı Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exe Güncellenemedi. Sebebi:.
        /// </summary>
        internal static string Exe_Güncellenemedi__Sebebi_ {
            get {
                return ResourceManager.GetString("Exe Güncellenemedi. Sebebi:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farklı Tarihler için Mahsup Oluşturulamaz....
        /// </summary>
        internal static string Farklı_Tarihler_için_Mahsup_Oluşturulamaz___ {
            get {
                return ResourceManager.GetString("Farklı Tarihler için Mahsup Oluşturulamaz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farklı Tarihteki Fişi İptal Edemezsiniz....
        /// </summary>
        internal static string Farklı_Tarihteki_Fişi_İptal_Edemezsiniz___ {
            get {
                return ResourceManager.GetString("Farklı Tarihteki Fişi İptal Edemezsiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farklı Tarihteki Masayı Geri Alamazsınız....
        /// </summary>
        internal static string Farklı_Tarihteki_Masayı_Geri_Alamazsınız___ {
            get {
                return ResourceManager.GetString("Farklı Tarihteki Masayı Geri Alamazsınız...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Dizaynı Yapılmamış....
        /// </summary>
        internal static string Fatura_Dizaynı_Yapılmamış___ {
            get {
                return ResourceManager.GetString("Fatura Dizaynı Yapılmamış...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Dizaynı Yapılmamış...!.
        /// </summary>
        internal static string Fatura_Dizaynı_Yapılmamış____ {
            get {
                return ResourceManager.GetString("Fatura Dizaynı Yapılmamış...!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturayı İptal Etmek İstiyormusunuz?.
        /// </summary>
        internal static string Faturayı_İptal_Etmek_İstiyormusunuz_ {
            get {
                return ResourceManager.GetString("Faturayı İptal Etmek İstiyormusunuz?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FİŞ LİMİTİ AŞILDI...FİŞ İPTAL EDİLİYOR....
        /// </summary>
        internal static string FİŞ_LİMİTİ_AŞILDI___FİŞ_İPTAL_EDİLİYOR___ {
            get {
                return ResourceManager.GetString("FİŞ LİMİTİ AŞILDI...FİŞ İPTAL EDİLİYOR...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio Bulunamadı...\nLütfen Hesabı Tekrar Kapatın....
        /// </summary>
        internal static string Folio_Bulunamadı____nLütfen_Hesabı_Tekrar_Kapatın___ {
            get {
                return ResourceManager.GetString("Folio Bulunamadı...\\nLütfen Hesabı Tekrar Kapatın...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio Numarasını Check Out Yapmak İstediğinize Eminmisiniz ?.
        /// </summary>
        internal static string Folio_Numarasını_Check_Out_Yapmak_İstediğinize_Eminmisiniz__ {
            get {
                return ResourceManager.GetString("Folio Numarasını Check Out Yapmak İstediğinize Eminmisiniz ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio Numarasını Silmek İstediğinize Eminmisiniz ?.
        /// </summary>
        internal static string Folio_Numarasını_Silmek_İstediğinize_Eminmisiniz__ {
            get {
                return ResourceManager.GetString("Folio Numarasını Silmek İstediğinize Eminmisiniz ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garson Seçiniz....
        /// </summary>
        internal static string Garson_Seçiniz___ {
            get {
                return ResourceManager.GetString("Garson Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçmiş Tarihe Ait Ödeme Bilgileri Değiştirilemez....
        /// </summary>
        internal static string Geçmiş_Tarihe_Ait_Ödeme_Bilgileri_Değiştirilemez___ {
            get {
                return ResourceManager.GetString("Geçmiş Tarihe Ait Ödeme Bilgileri Değiştirilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelir Hesaplar için Mahsup Kesmek İstiyor Musunuz ?.
        /// </summary>
        internal static string Gelir_Hesaplar_için_Mahsup_Kesmek_İstiyor_Musunuz__ {
            get {
                return ResourceManager.GetString("Gelir Hesaplar için Mahsup Kesmek İstiyor Musunuz ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelir Hesapları için Fis Oluştu.... Fis No :.
        /// </summary>
        internal static string Gelir_Hesapları_için_Fis_Oluştu_____Fis_No__ {
            get {
                return ResourceManager.GetString("Gelir Hesapları için Fis Oluştu.... Fis No :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş-Çıkış Kodunu,Tutarı yada Adı yanlış girdiniz....
        /// </summary>
        internal static string Giriş_Çıkış_Kodunu_Tutarı_yada_Adı_yanlış_girdiniz___ {
            get {
                return ResourceManager.GetString("Giriş-Çıkış Kodunu,Tutarı yada Adı yanlış girdiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grup İsmi Boş Geçilemez..
        /// </summary>
        internal static string Grup_İsmi_Boş_Geçilemez_ {
            get {
                return ResourceManager.GetString("Grup İsmi Boş Geçilemez.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleme için FTP server a bağlantı kurulamadı..
        /// </summary>
        internal static string Güncelleme_için_FTP_server_a_bağlantı_kurulamadı_ {
            get {
                return ResourceManager.GetString("Güncelleme için FTP server a bağlantı kurulamadı.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleme Tamamlandı. Program Kapatılacak..
        /// </summary>
        internal static string Güncelleme_Tamamlandı__Program_Kapatılacak_ {
            get {
                return ResourceManager.GetString("Güncelleme Tamamlandı. Program Kapatılacak.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günsonu Işlemi Tamamlandı....
        /// </summary>
        internal static string Günsonu_Işlemi_Tamamlandı___ {
            get {
                return ResourceManager.GetString("Günsonu Işlemi Tamamlandı...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programı Kapatıp\nYeniden Programa Giriş Yapmanız Gerekmektedir....
        /// </summary>
        internal static string Günsonu_Işlemi_Tamamlandı____nProgramı_Kapatıp_Yeniden_Programa_Giriş_Yapmanız_Gerekmektedir____ {
            get {
                return ResourceManager.GetString("Günsonu Işlemi Tamamlandı...\\nProgramı Kapatıp Yeniden Programa Giriş Yapmanız Ge" +
                        "rekmektedir....", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günsonu Şifreniz Yanlış....
        /// </summary>
        internal static string Günsonu_Şifreniz_Yanlış___ {
            get {
                return ResourceManager.GetString("Günsonu Şifreniz Yanlış...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hareket Görmüş, Silinemez..
        /// </summary>
        internal static string Hareket_Görmüş__Silinemez_ {
            get {
                return ResourceManager.GetString("Hareket Görmüş, Silinemez.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        internal static string Hata {
            get {
                return ResourceManager.GetString("Hata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalı giriş....
        /// </summary>
        internal static string Hatalı_giriş___ {
            get {
                return ResourceManager.GetString("Hatalı giriş...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Bulunamadı....
        /// </summary>
        internal static string Hesap_Bulunamadı___ {
            get {
                return ResourceManager.GetString("Hesap Bulunamadı...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlgili Alanları Doldurunuz...!.
        /// </summary>
        internal static string İlgili_Alanları_Doldurunuz____ {
            get {
                return ResourceManager.GetString("İlgili Alanları Doldurunuz...!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlgili Server Bilgileri Yoktur..
        /// </summary>
        internal static string İlgili_Server_Bilgileri_Yoktur_ {
            get {
                return ResourceManager.GetString("İlgili Server Bilgileri Yoktur.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Başarısız..
        /// </summary>
        internal static string İşlem_Başarısız_ {
            get {
                return ResourceManager.GetString("İşlem Başarısız.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Işlem Gecersiz..
        /// </summary>
        internal static string Işlem_Gecersiz_ {
            get {
                return ResourceManager.GetString("Işlem Gecersiz.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Tamamlandı..
        /// </summary>
        internal static string İşlem_Tamamlandı_ {
            get {
                return ResourceManager.GetString("İşlem Tamamlandı.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalan Bakiye :.
        /// </summary>
        internal static string Kalan_Bakiye__ {
            get {
                return ResourceManager.GetString("Kalan Bakiye :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapalı Çekler Sayısı ve Tutarı.
        /// </summary>
        internal static string Kapalı_Çekler_Sayısı_ve_Tutarı {
            get {
                return ResourceManager.GetString("Kapalı Çekler Sayısı ve Tutarı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapalı Masa Kişi Sayısı :.
        /// </summary>
        internal static string Kapalı_Masa_Kişi_Sayısı__ {
            get {
                return ResourceManager.GetString("Kapalı Masa Kişi Sayısı :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapanış Açılış, yapıldı..
        /// </summary>
        internal static string Kapanış_Açılış__yapıldı_ {
            get {
                return ResourceManager.GetString("Kapanış Açılış, yapıldı.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapatılmamış Çekler Bulunuyor. Lütfen Bütün Çeklerin Kapalı Olduğuna Emin Olun....
        /// </summary>
        internal static string Kapatılmamış_Çekler_Bulunuyor__Lütfen_Bütün_Çeklerin_Kapalı_Olduğuna_Emin_Olun___ {
            get {
                return ResourceManager.GetString("Kapatılmamış Çekler Bulunuyor. Lütfen Bütün Çeklerin Kapalı Olduğuna Emin Olun..." +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapatma Hesabını Seciniz....
        /// </summary>
        internal static string Kapatma_Hesabını_Seciniz___ {
            get {
                return ResourceManager.GetString("Kapatma Hesabını Seciniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapatma Kodunu Seçiniz....
        /// </summary>
        internal static string Kapatma_Kodunu_Seçiniz___ {
            get {
                return ResourceManager.GetString("Kapatma Kodunu Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Kayıtlıdır. Yeni Kart Deneyiniz...
        /// </summary>
        internal static string Kart_Kayıtlıdır__Yeni_Kart_Deneyiniz__ {
            get {
                return ResourceManager.GetString("Kart Kayıtlıdır. Yeni Kart Deneyiniz..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart limit Iadesi Yapılamaz...
        /// </summary>
        internal static string Kart_limit_Iadesi_Yapılamaz__ {
            get {
                return ResourceManager.GetString("Kart limit Iadesi Yapılamaz..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Okutunuz....
        /// </summary>
        internal static string Kart_Okutunuz___ {
            get {
                return ResourceManager.GetString("Kart Okutunuz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartlara Check Out İşlemi Uygulandı..
        /// </summary>
        internal static string Kartlara_Check_Out_İşlemi_Uygulandı_ {
            get {
                return ResourceManager.GetString("Kartlara Check Out İşlemi Uygulandı.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Edildi...
        /// </summary>
        internal static string Kayıt_Edildi__ {
            get {
                return ResourceManager.GetString("Kayıt Edildi..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı Restoran Bilgileri Bulunamadı...
        /// </summary>
        internal static string Kayıtlı_Restoran_Bilgileri_Bulunamadı__ {
            get {
                return ResourceManager.GetString("Kayıtlı Restoran Bilgileri Bulunamadı..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kişi Bilgisi Bulunamadı...
        /// </summary>
        internal static string Kişi_Bilgisi_Bulunamadı__ {
            get {
                return ResourceManager.GetString("Kişi Bilgisi Bulunamadı..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kişi Sayısını 10nun üzerindendir. Devam Etmek İstiyormusunuz?.
        /// </summary>
        internal static string Kişi_Sayısını_10nun_üzerindendir__Devam_Etmek_İstiyormusunuz_ {
            get {
                return ResourceManager.GetString("Kişi Sayısını 10nun üzerindendir. Devam Etmek İstiyormusunuz?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KİŞİ veya ŞİRKET Olarak Belirtiniz...
        /// </summary>
        internal static string KİŞİ_veya_ŞİRKET_Olarak_Belirtiniz__ {
            get {
                return ResourceManager.GetString("KİŞİ veya ŞİRKET Olarak Belirtiniz..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KK Hesaplar için Fis Oluştu.... Fis No :.
        /// </summary>
        internal static string KK_Hesaplar_için_Fis_Oluştu_____Fis_No__ {
            get {
                return ResourceManager.GetString("KK Hesaplar için Fis Oluştu.... Fis No :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KK Hesaplar için Mahsup Kesmek İstiyor Musunuz ?.
        /// </summary>
        internal static string KK_Hesaplar_için_Mahsup_Kesmek_İstiyor_Musunuz__ {
            get {
                return ResourceManager.GetString("KK Hesaplar için Mahsup Kesmek İstiyor Musunuz ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod Bos Gecilemez....
        /// </summary>
        internal static string Kod_Bos_Gecilemez___ {
            get {
                return ResourceManager.GetString("Kod Bos Gecilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol ediniz....
        /// </summary>
        internal static string Kontrol_ediniz___ {
            get {
                return ResourceManager.GetString("Kontrol ediniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konum Kod Boş Geçilemez....
        /// </summary>
        internal static string Konum_Kod_Boş_Geçilemez___ {
            get {
                return ResourceManager.GetString("Konum Kod Boş Geçilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KREDİ KARTI ÇEKİMİ GERÇEKLEŞTİRİLEMEDİ..HATA :.
        /// </summary>
        internal static string KREDİ_KARTI_ÇEKİMİ_GERÇEKLEŞTİRİLEMEDİ__HATA__ {
            get {
                return ResourceManager.GetString("KREDİ KARTI ÇEKİMİ GERÇEKLEŞTİRİLEMEDİ..HATA :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Kartları İşlendi..
        /// </summary>
        internal static string Kredi_Kartları_İşlendi_ {
            get {
                return ResourceManager.GetString("Kredi Kartları İşlendi.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KrediKarti Kontrol.
        /// </summary>
        internal static string KrediKarti_Kontrol {
            get {
                return ResourceManager.GetString("KrediKarti Kontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KrediKartı Odeme Uygulaması Bulunamadı..
        /// </summary>
        internal static string KrediKartı_Odeme_Uygulaması_Bulunamadı_ {
            get {
                return ResourceManager.GetString("KrediKartı Odeme Uygulaması Bulunamadı.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Kodu Bos Geçilemez...!!!.
        /// </summary>
        internal static string Kullanıcı_Kodu_Bos_Geçilemez______ {
            get {
                return ResourceManager.GetString("Kullanıcı Kodu Bos Geçilemez...!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Şifreniz Yanlış....
        /// </summary>
        internal static string Kullanıcı_Şifreniz_Yanlış___ {
            get {
                return ResourceManager.GetString("Kullanıcı Şifreniz Yanlış...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurlar Kaydedildi....
        /// </summary>
        internal static string Kurlar_Kaydedildi___ {
            get {
                return ResourceManager.GetString("Kurlar Kaydedildi...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listeden Müşteriyi Seçiniz....
        /// </summary>
        internal static string Listeden_Müşteriyi_Seçiniz___ {
            get {
                return ResourceManager.GetString("Listeden Müşteriyi Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listeneden Kişi Seçiniz....
        /// </summary>
        internal static string Listeneden_Kişi_Seçiniz___ {
            get {
                return ResourceManager.GetString("Listeneden Kişi Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lüften Resepsiyon ile Görüşün....
        /// </summary>
        internal static string Lüften_Resepsiyon_ile_Görüşün___ {
            get {
                return ResourceManager.GetString("Lüften Resepsiyon ile Görüşün...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Alt Grup Seçiniz....
        /// </summary>
        internal static string Lütfen_Alt_Grup_Seçiniz___ {
            get {
                return ResourceManager.GetString("Lütfen Alt Grup Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Ana Grup Seçiniz....
        /// </summary>
        internal static string Lütfen_Ana_Grup_Seçiniz___ {
            get {
                return ResourceManager.GetString("Lütfen Ana Grup Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Hesabı Tekrar Kapatın....
        /// </summary>
        internal static string Lütfen_Hesabı_Tekrar_Kapatın___ {
            get {
                return ResourceManager.GetString("Lütfen Hesabı Tekrar Kapatın...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Hesap Seçiniz....
        /// </summary>
        internal static string Lütfen_Hesap_Seçiniz___ {
            get {
                return ResourceManager.GetString("Lütfen Hesap Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Kapatma Hesabı Tanıtınız...
        /// </summary>
        internal static string Lütfen_Kapatma_Hesabı_Tanıtınız__ {
            get {
                return ResourceManager.GetString("Lütfen Kapatma Hesabı Tanıtınız..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Kapatma Kodu Tanıtınız...
        /// </summary>
        internal static string Lütfen_Kapatma_Kodu_Tanıtınız__ {
            get {
                return ResourceManager.GetString("Lütfen Kapatma Kodu Tanıtınız..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Kullanıcı Kodlarından PR Tanımlayınız....
        /// </summary>
        internal static string Lütfen_Kullanıcı_Kodlarından_PR_Tanımlayınız___ {
            get {
                return ResourceManager.GetString("Lütfen Kullanıcı Kodlarından PR Tanımlayınız...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Şube Seçiniz...
        /// </summary>
        internal static string Lütfen_Şube_Seçiniz__ {
            get {
                return ResourceManager.GetString("Lütfen Şube Seçiniz..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Başarıyla Gönderildi..
        /// </summary>
        internal static string Mail_Başarıyla_Gönderildi_ {
            get {
                return ResourceManager.GetString("Mail Başarıyla Gönderildi.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Gönderilemedi....
        /// </summary>
        internal static string Mail_Gönderilemedi___ {
            get {
                return ResourceManager.GetString("Mail Gönderilemedi...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masa Bilgisi Bulunamadı....
        /// </summary>
        internal static string Masa_Bilgisi_Bulunamadı___ {
            get {
                return ResourceManager.GetString("Masa Bilgisi Bulunamadı...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masa İzinleri Açıldı...
        /// </summary>
        internal static string Masa_İzinleri_Açıldı__ {
            get {
                return ResourceManager.GetString("Masa İzinleri Açıldı..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masa Numarı Boş Geçilemez....
        /// </summary>
        internal static string Masa_Numarı_Boş_Geçilemez___ {
            get {
                return ResourceManager.GetString("Masa Numarı Boş Geçilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masa Satışa Kapalı....
        /// </summary>
        internal static string Masa_Satışa_Kapalı___ {
            get {
                return ResourceManager.GetString("Masa Satışa Kapalı...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masa Seçiniz....
        /// </summary>
        internal static string Masa_Seçiniz___ {
            get {
                return ResourceManager.GetString("Masa Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masayı.
        /// </summary>
        internal static string Masayı {
            get {
                return ResourceManager.GetString("Masayı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max İndirim Yüzdeniz : %.
        /// </summary>
        internal static string Max_İndirim_Yüzdeniz____ {
            get {
                return ResourceManager.GetString("Max İndirim Yüzdeniz : %", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Indirim Yuzdesini Aştınız....
        /// </summary>
        internal static string Max_Indirim_Yuzdesini_Aştınız___ {
            get {
                return ResourceManager.GetString("Max Indirim Yuzdesini Aştınız...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Miktarı Geçtiniz....
        /// </summary>
        internal static string Maximum_Miktarı_Geçtiniz___ {
            get {
                return ResourceManager.GetString("Maximum Miktarı Geçtiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Getirilmeden Önce Eski Veriler Silinecektir. Emin misiniz ?.
        /// </summary>
        internal static string Menu_Getirilmeden_Önce_Eski_Veriler_Silinecektir__Emin_misiniz__ {
            get {
                return ResourceManager.GetString("Menu Getirilmeden Önce Eski Veriler Silinecektir. Emin misiniz ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut Cari için Açık çek bulunmaktadır. Açık çek üzerinde devam etmek istiyor musunuz?.
        /// </summary>
        internal static string Mevcut_Cari_için_Açık_çek_bulunmaktadır__Açık_çek_üzerinde_devam_etmek_istiyor_musunuz_ {
            get {
                return ResourceManager.GetString("Mevcut Cari için Açık çek bulunmaktadır. Açık çek üzerinde devam etmek istiyor mu" +
                        "sunuz?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakit Hesaplar için Fis Oluştu.... Fis No :.
        /// </summary>
        internal static string Nakit_Hesaplar_için_Fis_Oluştu_____Fis_No__ {
            get {
                return ResourceManager.GetString("Nakit Hesaplar için Fis Oluştu.... Fis No :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakit Hesaplar için Mahsup Kesmek İstiyor Musunuz ?.
        /// </summary>
        internal static string Nakit_Hesaplar_için_Mahsup_Kesmek_İstiyor_Musunuz__ {
            get {
                return ResourceManager.GetString("Nakit Hesaplar için Mahsup Kesmek İstiyor Musunuz ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakitler İşlendi..
        /// </summary>
        internal static string Nakitler_İşlendi_ {
            get {
                return ResourceManager.GetString("Nakitler İşlendi.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL Hesap Bakiye Yetersizdir.
        /// </summary>
        internal static string NL_Hesap_Bakiye_Yetersizdir {
            get {
                return ResourceManager.GetString("NL Hesap Bakiye Yetersizdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL Hesap Bakiye Yetersizdir..
        /// </summary>
        internal static string NL_Hesap_Bakiye_Yetersizdir_ {
            get {
                return ResourceManager.GetString("NL Hesap Bakiye Yetersizdir.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL Hesap Bakiye Yetersizdir..Kalan Bakiye :.
        /// </summary>
        internal static string NL_Hesap_Bakiye_Yetersizdir__Kalan_Bakiye__ {
            get {
                return ResourceManager.GetString("NL Hesap Bakiye Yetersizdir..Kalan Bakiye :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL Masa Şuan Dolu Masa Geri Alınamıyor....
        /// </summary>
        internal static string NL_Masa_Şuan_Dolu_Masa_Geri_Alınamıyor___ {
            get {
                return ResourceManager.GetString("NL Masa Şuan Dolu Masa Geri Alınamıyor...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nolu Fisin Fatura Numarası Değişti....
        /// </summary>
        internal static string Nolu_Fisin_Fatura_Numarası_Değişti___ {
            get {
                return ResourceManager.GetString("Nolu Fisin Fatura Numarası Değişti...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda Check-Out Olmuştur.Kayıt İşlemi İptal Edilmiştir..
        /// </summary>
        internal static string Oda_Check_Out_Olmuştur_Kayıt_İşlemi_İptal_Edilmiştir_ {
            get {
                return ResourceManager.GetString("Oda Check-Out Olmuştur.Kayıt İşlemi İptal Edilmiştir.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda In-House Değildir..
        /// </summary>
        internal static string Oda_In_House_Değildir_ {
            get {
                return ResourceManager.GetString("Oda In-House Değildir.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Alındı Fakat Hesap Kapanmadı....
        /// </summary>
        internal static string Ödeme_Alındı_Fakat_Hesap_Kapanmadı___ {
            get {
                return ResourceManager.GetString("Ödeme Alındı Fakat Hesap Kapanmadı...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODEME GERÇEKLEŞTİRİLEMEDİ... Tekrar Deneyiniz.
        /// </summary>
        internal static string ODEME_GERÇEKLEŞTİRİLEMEDİ____Tekrar_Deneyiniz {
            get {
                return ResourceManager.GetString("ODEME GERÇEKLEŞTİRİLEMEDİ... Tekrar Deneyiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Kodu Boş Geçilemez....
        /// </summary>
        internal static string Ödeme_Kodu_Boş_Geçilemez___ {
            get {
                return ResourceManager.GetString("Ödeme Kodu Boş Geçilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Kodu Satırını Seçiniz...
        /// </summary>
        internal static string Ödeme_Kodu_Satırını_Seçiniz__ {
            get {
                return ResourceManager.GetString("Ödeme Kodu Satırını Seçiniz..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Tutarını Kontrol ediniz..
        /// </summary>
        internal static string Ödeme_Tutarını_Kontrol_ediniz_ {
            get {
                return ResourceManager.GetString("Ödeme Tutarını Kontrol ediniz.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Tutarlarında Bir Yanlışlık Var..
        /// </summary>
        internal static string Ödeme_Tutarlarında_Bir_Yanlışlık_Var_ {
            get {
                return ResourceManager.GetString("Ödeme Tutarlarında Bir Yanlışlık Var.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödemeler veya İndirimler Silinemez...
        /// </summary>
        internal static string Ödemeler_veya_İndirimler_Silinemez__ {
            get {
                return ResourceManager.GetString("Ödemeler veya İndirimler Silinemez..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödemelere veya İndirimlere Açıklama Girilemez...
        /// </summary>
        internal static string Ödemelere_veya_İndirimlere_Açıklama_Girilemez__ {
            get {
                return ResourceManager.GetString("Ödemelere veya İndirimlere Açıklama Girilemez..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖDEMEYİ TEKRARDAN GERÇEKLEŞTİRMEK İSTİYORMUSUNUZ ?.
        /// </summary>
        internal static string ÖDEMEYİ_TEKRARDAN_GERÇEKLEŞTİRMEK_İSTİYORMUSUNUZ__ {
            get {
                return ResourceManager.GetString("ÖDEMEYİ TEKRARDAN GERÇEKLEŞTİRMEK İSTİYORMUSUNUZ ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖKC Üzerinde Yemek Ceki Ödeme Uygulanaması Bulunamadı.
        /// </summary>
        internal static string ÖKC_Üzerinde_Yemek_Ceki_Ödeme_Uygulanaması_Bulunamadı {
            get {
                return ResourceManager.GetString("ÖKC Üzerinde Yemek Ceki Ödeme Uygulanaması Bulunamadı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önbüro Çalışma Tarihi ile Sistem tarihi Farklı..
        /// </summary>
        internal static string Önbüro_Çalışma_Tarihi_ile_Sistem_tarihi_Farklı_ {
            get {
                return ResourceManager.GetString("Önbüro Çalışma Tarihi ile Sistem tarihi Farklı.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önbüro Çalışma Tarihi ile Sistem tarihi Farklı.\nSistemden Çıkıp Yeniden Giriniz....
        /// </summary>
        internal static string Önbüro_Çalışma_Tarihi_ile_Sistem_tarihi_Farklı__nSistemden_Çıkıp_Yeniden_Giriniz___ {
            get {
                return ResourceManager.GetString("Önbüro Çalışma Tarihi ile Sistem tarihi Farklı.\\nSistemden Çıkıp Yeniden Giriniz." +
                        "..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önbüro Çalışma Tarihi ile Sistem tarihi Farklı.Sistemden Çıkıp Yeniden Giriniz....
        /// </summary>
        internal static string Önbüro_Çalışma_Tarihi_ile_Sistem_tarihi_Farklı_Sistemden_Çıkıp_Yeniden_Giriniz___ {
            get {
                return ResourceManager.GetString("Önbüro Çalışma Tarihi ile Sistem tarihi Farklı.Sistemden Çıkıp Yeniden Giriniz..." +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos Tarih:.
        /// </summary>
        internal static string PosTar_ {
            get {
                return ResourceManager.GetString("PosTar:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programı Kapatıp.
        /// </summary>
        internal static string Programı_Kapatıp {
            get {
                return ResourceManager.GetString("Programı Kapatıp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programı Kapatıp\nYeniden Programa Giriş Yapmanız Gerekmektedir....
        /// </summary>
        internal static string Programı_Kapatıp_nYeniden_Programa_Giriş_Yapmanız_Gerekmektedir___ {
            get {
                return ResourceManager.GetString("Programı Kapatıp\\nYeniden Programa Giriş Yapmanız Gerekmektedir...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRAMI KAPATMAK İSTEDİĞİNİZE EMİN MİSİNİZ?.
        /// </summary>
        internal static string PROGRAMI_KAPATMAK_İSTEDİĞİNİZE_EMİN_MİSİNİZ_ {
            get {
                return ResourceManager.GetString("PROGRAMI KAPATMAK İSTEDİĞİNİZE EMİN MİSİNİZ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapor Adı Girmelisiniz....
        /// </summary>
        internal static string Rapor_Adı_Girmelisiniz___ {
            get {
                return ResourceManager.GetString("Rapor Adı Girmelisiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapor Dataya Kaydedilsin mi...?.
        /// </summary>
        internal static string Rapor_Dataya_Kaydedilsin_mi____ {
            get {
                return ResourceManager.GetString("Rapor Dataya Kaydedilsin mi...?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapor kayıt işlemi basarısız, Lütfen tekrar deneyiniz....
        /// </summary>
        internal static string Rapor_kayıt_işlemi_basarısız__Lütfen_tekrar_deneyiniz___ {
            get {
                return ResourceManager.GetString("Rapor kayıt işlemi basarısız, Lütfen tekrar deneyiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervasyon Silmek İstiyor Musunuz...?.
        /// </summary>
        internal static string Rezervasyon_Silmek_İstiyor_Musunuz____ {
            get {
                return ResourceManager.GetString("Rezervasyon Silmek İstiyor Musunuz...?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadece Genel Çek Raporundan Fişi Detayına Gidebilirsiniz....
        /// </summary>
        internal static string Sadece_Genel_Çek_Raporundan_Fişi_Detayına_Gidebilirsiniz___ {
            get {
                return ResourceManager.GetString("Sadece Genel Çek Raporundan Fişi Detayına Gidebilirsiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadece Genel Çek Raporundan Fişi İptal Edebilirsiniz....
        /// </summary>
        internal static string Sadece_Genel_Çek_Raporundan_Fişi_İptal_Edebilirsiniz___ {
            get {
                return ResourceManager.GetString("Sadece Genel Çek Raporundan Fişi İptal Edebilirsiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadece Genel Çek Raporundan Masa Geri Alabilirsiniz....
        /// </summary>
        internal static string Sadece_Genel_Çek_Raporundan_Masa_Geri_Alabilirsiniz___ {
            get {
                return ResourceManager.GetString("Sadece Genel Çek Raporundan Masa Geri Alabilirsiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadece Ödeme Satırı Silinebilir....
        /// </summary>
        internal static string Sadece_Ödeme_Satırı_Silinebilir___ {
            get {
                return ResourceManager.GetString("Sadece Ödeme Satırı Silinebilir...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış İşlemi Gerçekleşecektir..
        /// </summary>
        internal static string Satış_İşlemi_Gerçekleşecektir_ {
            get {
                return ResourceManager.GetString("Satış İşlemi Gerçekleşecektir.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış yapmadan önce Adisyon Numarasını giriniz....
        /// </summary>
        internal static string Satış_yapmadan_önce_Adisyon_Numarasını_giriniz___ {
            get {
                return ResourceManager.GetString("Satış yapmadan önce Adisyon Numarasını giriniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen Hesap Harcamaya Kapatılmıştır..
        /// </summary>
        internal static string Seçilen_Hesap_Harcamaya_Kapatılmıştır_ {
            get {
                return ResourceManager.GetString("Seçilen Hesap Harcamaya Kapatılmıştır.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen Hesap Harcamaya Kapatılmıştır.\nSatış İşlemi Gerçekleşecektir..
        /// </summary>
        internal static string Seçilen_Hesap_Harcamaya_Kapatılmıştır__nSatış_İşlemi_Gerçekleşecektir_ {
            get {
                return ResourceManager.GetString("Seçilen Hesap Harcamaya Kapatılmıştır.\\nSatış İşlemi Gerçekleşecektir.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen Hesap Kapatılmıştır..
        /// </summary>
        internal static string Seçilen_Hesap_Kapatılmıştır_ {
            get {
                return ResourceManager.GetString("Seçilen Hesap Kapatılmıştır.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili Hesap Limit Tutarını Aşmıştır..
        /// </summary>
        internal static string Seçili_Hesap_Limit_Tutarını_Aşmıştır_ {
            get {
                return ResourceManager.GetString("Seçili Hesap Limit Tutarını Aşmıştır.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili Kaydı Silmek İstediğinize Emin misiniz...?.
        /// </summary>
        internal static string Seçili_Kaydı_Silmek_İstediğinize_Emin_misiniz____ {
            get {
                return ResourceManager.GetString("Seçili Kaydı Silmek İstediğinize Emin misiniz...?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili Kaydı Zayi Yapmak İstediğinize Emin Misiniz...?.
        /// </summary>
        internal static string Seçili_Kaydı_Zayi_Yapmak_İstediğinize_Emin_Misiniz____ {
            get {
                return ResourceManager.GetString("Seçili Kaydı Zayi Yapmak İstediğinize Emin Misiniz...?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili Masaları Silmek İstediğinize Emin Misiniz...?.
        /// </summary>
        internal static string Seçili_Masaları_Silmek_İstediğinize_Emin_Misiniz____ {
            get {
                return ResourceManager.GetString("Seçili Masaları Silmek İstediğinize Emin Misiniz...?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili Masayı Geri Almak İstiyor Musunuz?.
        /// </summary>
        internal static string Seçili_Masayı_Geri_Almak_İstiyor_Musunuz_ {
            get {
                return ResourceManager.GetString("Seçili Masayı Geri Almak İstiyor Musunuz?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secili Satırı Silmek İstediğineze Emin misiniz...?.
        /// </summary>
        internal static string Secili_Satırı_Silmek_İstediğineze_Emin_misiniz____ {
            get {
                return ResourceManager.GetString("Secili Satırı Silmek İstediğineze Emin misiniz...?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servis Payı Sayısı ve Tutarı.
        /// </summary>
        internal static string Servis_Payı_Sayısı_ve_Tutarı {
            get {
                return ResourceManager.GetString("Servis Payı Sayısı ve Tutarı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servis Zamanı Minumum 30DK , Maximum 75DK arasında olmalıdır...
        /// </summary>
        internal static string Servis_Zamanı_Minumum_30DK___Maximum_75DK_arasında_olmalıdır__ {
            get {
                return ResourceManager.GetString("Servis Zamanı Minumum 30DK , Maximum 75DK arasında olmalıdır..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinecek Kaydı Seçiniz....
        /// </summary>
        internal static string Silinecek_Kaydı_Seçiniz___ {
            get {
                return ResourceManager.GetString("Silinecek Kaydı Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silmek İstediğinize Emin misiniz ?.
        /// </summary>
        internal static string Silmek_İstediğinize_Emin_misiniz__ {
            get {
                return ResourceManager.GetString("Silmek İstediğinize Emin misiniz ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Yazıcıya Gönderilsin Mi...?.
        /// </summary>
        internal static string Sipariş_Yazıcıya_Gönderilsin_Mi____ {
            get {
                return ResourceManager.GetString("Sipariş Yazıcıya Gönderilsin Mi...?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişiniz Gönderildi..
        /// </summary>
        internal static string Siparişiniz_Gönderildi_ {
            get {
                return ResourceManager.GetString("Siparişiniz Gönderildi.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistem Tarihi ile Pos Tarihi Aynı Değil Kontrol Ediniz!!!.
        /// </summary>
        internal static string Sistem_Tarihi_ile_Pos_Tarihi_Aynı_Değil_Kontrol_Ediniz___ {
            get {
                return ResourceManager.GetString("Sistem Tarihi ile Pos Tarihi Aynı Değil Kontrol Ediniz!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistem Yeni Kod Versin mi?.
        /// </summary>
        internal static string Sistem_Yeni_Kod_Versin_mi_ {
            get {
                return ResourceManager.GetString("Sistem Yeni Kod Versin mi?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemden Çıkıp Yeniden Giriniz....
        /// </summary>
        internal static string Sistemden_Çıkıp_Yeniden_Giriniz___ {
            get {
                return ResourceManager.GetString("Sistemden Çıkıp Yeniden Giriniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistem Tarih:.
        /// </summary>
        internal static string SistemTar_ {
            get {
                return ResourceManager.GetString("SistemTar:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Ürün Eksiltilemez....
        /// </summary>
        internal static string Son_Ürün_Eksiltilemez___ {
            get {
                return ResourceManager.GetString("Son Ürün Eksiltilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sql&apos;e Aktarim Yapılırken Hata Olustu:.
        /// </summary>
        internal static string Sql_e_Aktarim_Yapılırken_Hata_Olustu_ {
            get {
                return ResourceManager.GetString("Sql\'e Aktarim Yapılırken Hata Olustu:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL kodunda hataya rastlandı.
        /// </summary>
        internal static string SQL_kodunda_hataya_rastlandı {
            get {
                return ResourceManager.GetString("SQL kodunda hataya rastlandı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sube Boş Geçilemez..
        /// </summary>
        internal static string Sube_Boş_Geçilemez_ {
            get {
                return ResourceManager.GetString("Sube Boş Geçilemez.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube Seçiniz...
        /// </summary>
        internal static string Şube_Seçiniz__ {
            get {
                return ResourceManager.GetString("Şube Seçiniz..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube Verileri Transfer edilecek. Eminmisiniz?.
        /// </summary>
        internal static string Şube_Verileri_Transfer_edilecek__Eminmisiniz_ {
            get {
                return ResourceManager.GetString("Şube Verileri Transfer edilecek. Eminmisiniz?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şubeden - Merkeze Satışlar Aktarıldı..
        /// </summary>
        internal static string Şubeden___Merkeze_Satışlar_Aktarıldı_ {
            get {
                return ResourceManager.GetString("Şubeden - Merkeze Satışlar Aktarıldı.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih Alanı Boş Geçilemez..
        /// </summary>
        internal static string Tarih_Alanı_Boş_Geçilemez_ {
            get {
                return ResourceManager.GetString("Tarih Alanı Boş Geçilemez.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarihindeki Günü Birlik Kartlara Check Out Uygulansın mı ?.
        /// </summary>
        internal static string Tarihindeki_Günü_Birlik_Kartlara_Check_Out_Uygulansın_mı__ {
            get {
                return ResourceManager.GetString("Tarihindeki Günü Birlik Kartlara Check Out Uygulansın mı ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarihindeki Toplu Gelir İade Kapatma Uygulansın mı ?.
        /// </summary>
        internal static string Tarihindeki_Toplu_Gelir_İade_Kapatma_Uygulansın_mı__ {
            get {
                return ResourceManager.GetString("Tarihindeki Toplu Gelir İade Kapatma Uygulansın mı ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarihli Kurlar Yoktur...Kur Girişinden Günlük Kurları Tanımlayabilirisiniz..
        /// </summary>
        internal static string Tarihli_Kurlar_Yoktur___Kur_Girişinden_Günlük_Kurları_Tanımlayabilirisiniz_ {
            get {
                return ResourceManager.GetString("Tarihli Kurlar Yoktur...Kur Girişinden Günlük Kurları Tanımlayabilirisiniz.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarihli Pos Satış Raporu Ektedir..
        /// </summary>
        internal static string Tarihli_Pos_Satış_Raporu_Ektedir_ {
            get {
                return ResourceManager.GetString("Tarihli Pos Satış Raporu Ektedir.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temassız Kartla Çalışan Tesisler İçin Geçerlidir..
        /// </summary>
        internal static string Temassız_Kartla_Çalışan_Tesisler_İçin_Geçerlidir_ {
            get {
                return ResourceManager.GetString("Temassız Kartla Çalışan Tesisler İçin Geçerlidir.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMEL FATURA veya TICARI FATURA Olarak Belirtiniz...
        /// </summary>
        internal static string TEMEL_FATURA_veya_TICARI_FATURA_Olarak_Belirtiniz__ {
            get {
                return ResourceManager.GetString("TEMEL FATURA veya TICARI FATURA Olarak Belirtiniz..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Maili Gönderildi....
        /// </summary>
        internal static string Test_Maili_Gönderildi___ {
            get {
                return ResourceManager.GetString("Test Maili Gönderildi...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam :.
        /// </summary>
        internal static string Toplam__ {
            get {
                return ResourceManager.GetString("Toplam :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Çekler Sayısı ve Tutarı.
        /// </summary>
        internal static string Toplam_Çekler_Sayısı_ve_Tutarı {
            get {
                return ResourceManager.GetString("Toplam Çekler Sayısı ve Tutarı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Masa Kişi Sayısı :.
        /// </summary>
        internal static string Toplam_Masa_Kişi_Sayısı__ {
            get {
                return ResourceManager.GetString("Toplam Masa Kişi Sayısı :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Alanları Doldurunuz...!.
        /// </summary>
        internal static string Tüm_Alanları_Doldurunuz____ {
            get {
                return ResourceManager.GetString("Tüm Alanları Doldurunuz...!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urun Grubu Bos Geçilemez....
        /// </summary>
        internal static string Urun_Grubu_Bos_Geçilemez___ {
            get {
                return ResourceManager.GetString("Urun Grubu Bos Geçilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Kodu Bulunamadı....
        /// </summary>
        internal static string Ürün_Kodu_Bulunamadı___ {
            get {
                return ResourceManager.GetString("Ürün Kodu Bulunamadı...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        internal static string Uyarı {
            get {
                return ResourceManager.GetString("Uyarı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi Daire ve Vergi No Alanlarını Doldurunuz...
        /// </summary>
        internal static string Vergi_Daire_ve_Vergi_No_Alanlarını_Doldurunuz__ {
            get {
                return ResourceManager.GetString("Vergi Daire ve Vergi No Alanlarını Doldurunuz..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazarkasa Eslestirmesiyle Gelen Departman(Kısım) VB. Bilgileri RMOS ULTIMATE POS&apos;a Aktarılacaktır \r\n Devam Etmek Istiyor musunuz.
        /// </summary>
        internal static string Yazarkasa_Eslestirmesiyle_Gelen_Departman_Kısım__VB__Bilgileri_RMOS_ULTIMATE_POS_a_Aktarılacaktır__r_n_Devam_Etmek_Istiyor_musunuz {
            get {
                return ResourceManager.GetString("Yazarkasa Eslestirmesiyle Gelen Departman(Kısım) VB. Bilgileri RMOS ULTIMATE POS\'" +
                        "a Aktarılacaktır \\r\\n Devam Etmek Istiyor musunuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazdırılmış Satır Silme Yetkiniz Yoktur...!.
        /// </summary>
        internal static string Yazdırılmış_Satır_Silme_Yetkiniz_Yoktur____ {
            get {
                return ResourceManager.GetString("Yazdırılmış Satır Silme Yetkiniz Yoktur...!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazılacak Alanı Seçiniz....
        /// </summary>
        internal static string Yazılacak_Alanı_Seçiniz___ {
            get {
                return ResourceManager.GetString("Yazılacak Alanı Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YemekSepeti Siparişleri için kullanılabilir..
        /// </summary>
        internal static string YemekSepeti_Siparişleri_için_kullanılabilir_ {
            get {
                return ResourceManager.GetString("YemekSepeti Siparişleri için kullanılabilir.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni tarih Sistem Server tarihinden Büyük Olamaz!!!!.
        /// </summary>
        internal static string Yeni_tarih_Sistem_Server_tarihinden_Büyük_Olamaz____ {
            get {
                return ResourceManager.GetString("Yeni tarih Sistem Server tarihinden Büyük Olamaz!!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeniden Programa Giriş Yapmanız Gerekmektedir....
        /// </summary>
        internal static string Yeniden_Programa_Giriş_Yapmanız_Gerekmektedir___ {
            get {
                return ResourceManager.GetString("Yeniden Programa Giriş Yapmanız Gerekmektedir...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yüklenecek Limit Tutarını Giriniz....
        /// </summary>
        internal static string Yüklenecek_Limit_Tutarını_Giriniz___ {
            get {
                return ResourceManager.GetString("Yüklenecek Limit Tutarını Giriniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yuvarlama Recetesi Tanımlı Değil....
        /// </summary>
        internal static string Yuvarlama_Recetesi_Tanımlı_Değil___ {
            get {
                return ResourceManager.GetString("Yuvarlama Recetesi Tanımlı Değil...", resourceCulture);
            }
        }
    }
}
