//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Class {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pos.Class.lang_ru", typeof(lang_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество людей за открытым столом :.
        /// </summary>
        internal static string Açık_Masa_Kişi_Sayısı__ {
            get {
                return ResourceManager.GetString("Açık Masa Kişi Sayısı :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете вернуть открытый стол....
        /// </summary>
        internal static string Açık_Masayı_Masayı_Geri_Alamazsınız___ {
            get {
                return ResourceManager.GetString("Açık Masayı Masayı Geri Alamazsınız...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openning Time :.
        /// </summary>
        internal static string Açılış_Saati__ {
            get {
                return ResourceManager.GetString("Açılış Saati :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыт. Другой не может продать...!!!.
        /// </summary>
        internal static string Açmıştır_Başkası_Satış_Yapamaz______ {
            get {
                return ResourceManager.GetString("Açmıştır.Başkası Satış Yapamaz...!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя не может быть пустым....
        /// </summary>
        internal static string Ad_Boş_Geçilemez___ {
            get {
                return ResourceManager.GetString("Ad Boş Geçilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя не может быть пустым....
        /// </summary>
        internal static string Ad_ve_Soyad_Boş_Geçilemez___ {
            get {
                return ResourceManager.GetString("Ad ve Soyad Boş Geçilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выписка бланка счет-заказа... Вы хотите продолжить ?.
        /// </summary>
        internal static string Adisyon_Dökülecek____Devam_Etmek_İstiyor_Musunuz__ {
            get {
                return ResourceManager.GetString("Adisyon Dökülecek... Devam Etmek İstiyor Musunuz ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбран принтер для бланка счет-заказа....
        /// </summary>
        internal static string Adisyon_için_Bir_Printer_Seçimi_Yapılmamış___ {
            get {
                return ResourceManager.GetString("Adisyon için Bir Printer Seçimi Yapılmamış...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Передача завершена \r\n Классы кода \r\n 91:Способы оплаты \r\n 92:Части отдела \r\n 93:Банки \r\n 94:Продовольственные чеки.
        /// </summary>
        internal static string Aktarim_Bitmistir__r_n_Kod_Sinifları__r_n_91_Odeme_Sekilleri__r_n_92_Departman_Kısımları__r_n_93_Bankalar__r_n_94_Yemek_Cekleri {
            get {
                return ResourceManager.GetString("Aktarim Bitmistir \\r\\n Kod Sinifları \\r\\n 91:Odeme Sekilleri \\r\\n 92:Departman Kı" +
                        "sımları \\r\\n 93:Bankalar \\r\\n 94:Yemek Cekleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перед передачей требуется сопряжение.
        /// </summary>
        internal static string Aktarım_Yapmadan_Once_Eslestirme_Yapılması_Gerekir {
            get {
                return ResourceManager.GetString("Aktarım Yapmadan Once Eslestirme Yapılması Gerekir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете совершать операции над строкой дебиторской задолженности….
        /// </summary>
        internal static string Alacak_Satırı_üzerinde_İşlem_Yapamazsınız___ {
            get {
                return ResourceManager.GetString("Alacak Satırı üzerinde İşlem Yapamazsınız...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основная группа не может быть пустой....
        /// </summary>
        internal static string Ana_Grup_Boş_Geçilemez___ {
            get {
                return ResourceManager.GetString("Ana Grup Boş Geçilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проблема с настройками....
        /// </summary>
        internal static string Ayarlarınızda_Sorun_Var___ {
            get {
                return ResourceManager.GetString("Ayarlarınızda Sorun Var...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тот же номер карты определен у другого пользователя. Измените номер карты....
        /// </summary>
        internal static string Aynı_Kart_Numarası_Başka_Kullanıcıda_Tanımlı__Kart_Numarasını_Değiştiriniz___ {
            get {
                return ResourceManager.GetString("Aynı Kart Numarası Başka Kullanıcıda Tanımlı. Kart Numarasını Değiştiriniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы загрузить баланс, выберите платежный отдел....
        /// </summary>
        internal static string Bakiye_Yüklemek_için_Ödeme_Departmanını_Seçiniz___ {
            get {
                return ResourceManager.GetString("Bakiye Yüklemek için Ödeme Departmanını Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс загружен....
        /// </summary>
        internal static string Bakiye_Yüklenmiştir___ {
            get {
                return ResourceManager.GetString("Bakiye Yüklenmiştir...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальные и конечные значения должны быть числовыми...!!!.
        /// </summary>
        internal static string Başlangıc_Bitiş_Değerleri_Sayısal_Olmalıdır______ {
            get {
                return ResourceManager.GetString("Başlangıc Bitiş Değerleri Sayısal Olmalıdır...!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите начальные и конечные значения....
        /// </summary>
        internal static string Baslangıc_ve_Bitis_Değerlerini_Giriniz___ {
            get {
                return ResourceManager.GetString("Baslangıc ve Bitis Değerlerini Giriniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string Bilgilendirme {
            get {
                return ResourceManager.GetString("Bilgilendirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден стол для сервиса на вынос..
        /// </summary>
        internal static string Boş_Paket_Masanız_Bulunmamaktadır_ {
            get {
                return ResourceManager.GetString("Boş Paket Masanız Bulunmamaktadır.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте настройки принтера этого отдела....
        /// </summary>
        internal static string Bu_Departmana_Ait_Yazıcı_Ayarlarını_Kontrol_Ediniz___ {
            get {
                return ResourceManager.GetString("Bu Departmana Ait Yazıcı Ayarlarını Kontrol Ediniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уже есть отчет с таким названием....
        /// </summary>
        internal static string Bu_isimde_zaten_bir_rapor_var___ {
            get {
                return ResourceManager.GetString("Bu isimde zaten bir rapor var...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не уполномочены выполнять эту операцию..
        /// </summary>
        internal static string Bu_İşlemi_Yapmaya_Yetkiniz_Yoktur_ {
            get {
                return ResourceManager.GetString("Bu İşlemi Yapmaya Yetkiniz Yoktur.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Name.
        /// </summary>
        internal static string Cari_Ad {
            get {
                return ResourceManager.GetString("Cari Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Address1.
        /// </summary>
        internal static string Cari_Adres1 {
            get {
                return ResourceManager.GetString("Cari Adres1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Address2.
        /// </summary>
        internal static string Cari_Adres2 {
            get {
                return ResourceManager.GetString("Cari Adres2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Address3.
        /// </summary>
        internal static string Cari_Adres3 {
            get {
                return ResourceManager.GetString("Cari Adres3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete Current Motion!.
        /// </summary>
        internal static string Cari_hareket_Görmüş_Silinemez_ {
            get {
                return ResourceManager.GetString("Cari hareket Görmüş Silinemez!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Card.
        /// </summary>
        internal static string Cari_Kart {
            get {
                return ResourceManager.GetString("Cari Kart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Code.
        /// </summary>
        internal static string Cari_Kod {
            get {
                return ResourceManager.GetString("Cari Kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Code Cannot Be Empty ....
        /// </summary>
        internal static string Cari_Kodu_Boş_Geçilemez___ {
            get {
                return ResourceManager.GetString("Cari Kodu Boş Geçilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Code Cannot Be Empty ... \n Does The System Automatically Create A New Code?.
        /// </summary>
        internal static string Cari_Kodu_Boş_Geçilemez____nSistem_Yeni_Kod_Versin_mi_ {
            get {
                return ResourceManager.GetString("Cari Kodu Boş Geçilemez...\\nSistem Yeni Kod Versin mi?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter account code.
        /// </summary>
        internal static string Cari_Kodu_Giriniz___ {
            get {
                return ResourceManager.GetString("Cari Kodu Giriniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account code is not defined..
        /// </summary>
        internal static string Cari_kodu_tanımlı_değil_ {
            get {
                return ResourceManager.GetString("Cari kodu tanımlı değil.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Surname.
        /// </summary>
        internal static string Cari_Soyad {
            get {
                return ResourceManager.GetString("Cari Soyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Phone.
        /// </summary>
        internal static string Cari_Tel {
            get {
                return ResourceManager.GetString("Cari Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Çıkış {
            get {
                return ResourceManager.GetString("Çıkış", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отдел не может быть пустым....
        /// </summary>
        internal static string Departman_Bos_Geçilemez___ {
            get {
                return ResourceManager.GetString("Departman Bos Geçilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить параметры отдела....
        /// </summary>
        internal static string Departman_Parametreleri_Yüklenemedi___ {
            get {
                return ResourceManager.GetString("Departman Parametreleri Yüklenemedi...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите продолжить?.
        /// </summary>
        internal static string Devam_etmek_İstiyor_musunuz__ {
            get {
                return ResourceManager.GetString("Devam etmek İstiyor musunuz ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите продолжить?.
        /// </summary>
        internal static string Devam_Etmek_İstiyor_Musunuz____ {
            get {
                return ResourceManager.GetString("Devam Etmek İstiyor Musunuz...?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить оформление....
        /// </summary>
        internal static string Dizany_Yüklenemedi___ {
            get {
                return ResourceManager.GetString("Dizany Yüklenemedi...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите запись для редактирования....
        /// </summary>
        internal static string Düzeltilecek_Kaydı_Seçiniz___ {
            get {
                return ResourceManager.GetString("Düzeltilecek Kaydı Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось обновить Exe. Причина:.
        /// </summary>
        internal static string Exe_Güncellenemedi__Sebebi_ {
            get {
                return ResourceManager.GetString("Exe Güncellenemedi. Sebebi:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно создать оборотную ведомость (Mahsup) для разных дат....
        /// </summary>
        internal static string Farklı_Tarihler_için_Mahsup_Oluşturulamaz___ {
            get {
                return ResourceManager.GetString("Farklı Tarihler için Mahsup Oluşturulamaz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете отменить квитанцию c другой датой....
        /// </summary>
        internal static string Farklı_Tarihteki_Fişi_İptal_Edemezsiniz___ {
            get {
                return ResourceManager.GetString("Farklı Tarihteki Fişi İptal Edemezsiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете вернуть стол с другой датой....
        /// </summary>
        internal static string Farklı_Tarihteki_Masayı_Geri_Alamazsınız___ {
            get {
                return ResourceManager.GetString("Farklı Tarihteki Masayı Geri Alamazsınız...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дизайн счета-фактуры не выполнен….
        /// </summary>
        internal static string Fatura_Dizaynı_Yapılmamış___ {
            get {
                return ResourceManager.GetString("Fatura Dizaynı Yapılmamış...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите отменить счет-фактуру?.
        /// </summary>
        internal static string Faturayı_İptal_Etmek_İstiyormusunuz_ {
            get {
                return ResourceManager.GetString("Faturayı İptal Etmek İstiyormusunuz?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фолио не найдено...\nПожалуйста, снова закройте счет....
        /// </summary>
        internal static string Folio_Bulunamadı____nLütfen_Hesabı_Tekrar_Kapatın___ {
            get {
                return ResourceManager.GetString("Folio Bulunamadı...\\nLütfen Hesabı Tekrar Kapatın...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите сделать Check Out?.
        /// </summary>
        internal static string Folio_Numarasını_Check_Out_Yapmak_İstediğinize_Eminmisiniz__ {
            get {
                return ResourceManager.GetString("Folio Numarasını Check Out Yapmak İstediğinize Eminmisiniz ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить номер фолио ?.
        /// </summary>
        internal static string Folio_Numarasını_Silmek_İstediğinize_Eminmisiniz__ {
            get {
                return ResourceManager.GetString("Folio Numarasını Silmek İstediğinize Eminmisiniz ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите официанта....
        /// </summary>
        internal static string Garson_Seçiniz___ {
            get {
                return ResourceManager.GetString("Garson Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите выписать счета для оборотных ведомостей (Mahsup).
        /// </summary>
        internal static string Gelir_Hesaplar_için_Mahsup_Kesmek_İstiyor_Musunuz__ {
            get {
                return ResourceManager.GetString("Gelir Hesaplar için Mahsup Kesmek İstiyor Musunuz ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квитанция была сформирована для счетов доходов.... № Квитанции:.
        /// </summary>
        internal static string Gelir_Hesapları_için_Fis_Oluştu_____Fis_No__ {
            get {
                return ResourceManager.GetString("Gelir Hesapları için Fis Oluştu.... Fis No :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter GRAMS....
        /// </summary>
        internal static string GRAM_Giriniz___ {
            get {
                return ResourceManager.GetString("GRAM Giriniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя группы не может быть пустым..
        /// </summary>
        internal static string Grup_İsmi_Boş_Geçilemez_ {
            get {
                return ResourceManager.GetString("Grup İsmi Boş Geçilemez.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось установить соединение с FTP-сервером для обновления..
        /// </summary>
        internal static string Güncelleme_için_FTP_server_a_bağlantı_kurulamadı_ {
            get {
                return ResourceManager.GetString("Güncelleme için FTP server a bağlantı kurulamadı.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процесс завершения дня готов....
        /// </summary>
        internal static string Günsonu_Işlemi_Tamamlandı___ {
            get {
                return ResourceManager.GetString("Günsonu Işlemi Tamamlandı...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль для завершения дня неверен....
        /// </summary>
        internal static string Günsonu_Şifreniz_Yanlış___ {
            get {
                return ResourceManager.GetString("Günsonu Şifreniz Yanlış...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Движение замечено, невозможно удалить..
        /// </summary>
        internal static string Hareket_Görmüş__Silinemez_ {
            get {
                return ResourceManager.GetString("Hareket Görmüş, Silinemez.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Hata {
            get {
                return ResourceManager.GetString("Hata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка входа....
        /// </summary>
        internal static string Hatalı_giriş___ {
            get {
                return ResourceManager.GetString("Hatalı giriş...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Счет не найден....
        /// </summary>
        internal static string Hesap_Bulunamadı___ {
            get {
                return ResourceManager.GetString("Hesap Bulunamadı...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните соответствующие поля...!.
        /// </summary>
        internal static string İlgili_Alanları_Doldurunuz____ {
            get {
                return ResourceManager.GetString("İlgili Alanları Doldurunuz...!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соответствующая информация о сервере отсутствует..
        /// </summary>
        internal static string İlgili_Server_Bilgileri_Yoktur_ {
            get {
                return ResourceManager.GetString("İlgili Server Bilgileri Yoktur.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER REASON FOR CANCELLATION....
        /// </summary>
        internal static string İPTAL_NEDENİNİ_GİRİNİZ___ {
            get {
                return ResourceManager.GetString("İPTAL NEDENİNİ GİRİNİZ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция не удалась..
        /// </summary>
        internal static string İşlem_Başarısız_ {
            get {
                return ResourceManager.GetString("İşlem Başarısız.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транзакция недействительна..
        /// </summary>
        internal static string Işlem_Gecersiz_ {
            get {
                return ResourceManager.GetString("Işlem Gecersiz.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция завершена..
        /// </summary>
        internal static string İşlem_Tamamlandı_ {
            get {
                return ResourceManager.GetString("İşlem Tamamlandı.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставшийся баланс :.
        /// </summary>
        internal static string Kalan_Bakiye__ {
            get {
                return ResourceManager.GetString("Kalan Bakiye :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество людей за закрытым столом :.
        /// </summary>
        internal static string Kapalı_Masa_Kişi_Sayısı__ {
            get {
                return ResourceManager.GetString("Kapalı Masa Kişi Sayısı :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрытие Открытие сделано..
        /// </summary>
        internal static string Kapanış_Açılış__yapıldı_ {
            get {
                return ResourceManager.GetString("Kapanış Açılış, yapıldı.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Есть незакрытые чеки. Пожалуйста, убедитесь, что все чеки закрыты....
        /// </summary>
        internal static string Kapatılmamış_Çekler_Bulunuyor__Lütfen_Bütün_Çeklerin_Kapalı_Olduğuna_Emin_Olun___ {
            get {
                return ResourceManager.GetString("Kapatılmamış Çekler Bulunuyor. Lütfen Bütün Çeklerin Kapalı Olduğuna Emin Olun..." +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта зарегистрирована. Попробуйте новую карту...
        /// </summary>
        internal static string Kart_Kayıtlıdır__Yeni_Kart_Deneyiniz__ {
            get {
                return ResourceManager.GetString("Kart Kayıtlıdır. Yeni Kart Deneyiniz..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возврат лимита карты не может быть произведен...
        /// </summary>
        internal static string Kart_limit_Iadesi_Yapılamaz__ {
            get {
                return ResourceManager.GetString("Kart limit Iadesi Yapılamaz..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Считайте карту....
        /// </summary>
        internal static string Kart_Okutunuz___ {
            get {
                return ResourceManager.GetString("Kart Okutunuz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К картам был применен процесс Check Out..
        /// </summary>
        internal static string Kartlara_Check_Out_İşlemi_Uygulandı_ {
            get {
                return ResourceManager.GetString("Kartlara Check Out İşlemi Uygulandı.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASE EXIT MOVEMENT.
        /// </summary>
        internal static string Kasa_Çıkış_Hareketi {
            get {
                return ResourceManager.GetString("Kasa Çıkış Hareketi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASE ENTRY MOVEMENT.
        /// </summary>
        internal static string Kasa_Giriş_Hareketi {
            get {
                return ResourceManager.GetString("Kasa Giriş Hareketi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись произведена...
        /// </summary>
        internal static string Kayıt_Edildi__ {
            get {
                return ResourceManager.GetString("Kayıt Edildi..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрированная информация о ресторане не найдена...
        /// </summary>
        internal static string Kayıtlı_Restoran_Bilgileri_Bulunamadı__ {
            get {
                return ResourceManager.GetString("Kayıtlı Restoran Bilgileri Bulunamadı..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактная информация не найдена...
        /// </summary>
        internal static string Kişi_Bilgisi_Bulunamadı__ {
            get {
                return ResourceManager.GetString("Kişi Bilgisi Bulunamadı..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Number of Persons....
        /// </summary>
        internal static string Kişi_Sayısı_Giriniz___ {
            get {
                return ResourceManager.GetString("Kişi Sayısı Giriniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество людей превышает 10 человек. Вы хотите продолжить?.
        /// </summary>
        internal static string Kişi_Sayısını_10nun_üzerindendir__Devam_Etmek_İstiyormusunuz_ {
            get {
                return ResourceManager.GetString("Kişi Sayısını 10nun üzerindendir. Devam Etmek İstiyormusunuz?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите как ЛИЦО или КОМПАНИЮ...
        /// </summary>
        internal static string KİŞİ_veya_ŞİRKET_Olarak_Belirtiniz__ {
            get {
                return ResourceManager.GetString("KİŞİ veya ŞİRKET Olarak Belirtiniz..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для КК счетов квитанция создана.... Квитанция №:.
        /// </summary>
        internal static string KK_Hesaplar_için_Fis_Oluştu_____Fis_No__ {
            get {
                return ResourceManager.GetString("KK Hesaplar için Fis Oluştu.... Fis No :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите  выписать оборотную ведомость (Mahsup) для КК счетов?.
        /// </summary>
        internal static string KK_Hesaplar_için_Mahsup_Kesmek_İstiyor_Musunuz__ {
            get {
                return ResourceManager.GetString("KK Hesaplar için Mahsup Kesmek İstiyor Musunuz ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код пустым не может быть....
        /// </summary>
        internal static string Kod_Bos_Gecilemez___ {
            get {
                return ResourceManager.GetString("Kod Bos Gecilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение не может быть пустым....
        /// </summary>
        internal static string Konum_Kod_Boş_Geçilemez___ {
            get {
                return ResourceManager.GetString("Konum Kod Boş Geçilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кредитные карты обработаны..
        /// </summary>
        internal static string Kredi_Kartları_İşlendi_ {
            get {
                return ResourceManager.GetString("Kredi Kartları İşlendi.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка кредитной карты.
        /// </summary>
        internal static string KrediKarti_Kontrol {
            get {
                return ResourceManager.GetString("KrediKarti Kontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение для оплаты кредитной картой не найдено..
        /// </summary>
        internal static string KrediKartı_Odeme_Uygulaması_Bulunamadı_ {
            get {
                return ResourceManager.GetString("KrediKartı Odeme Uygulaması Bulunamadı.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код пользователя не может быть пустым...!!!.
        /// </summary>
        internal static string Kullanıcı_Kodu_Bos_Geçilemez______ {
            get {
                return ResourceManager.GetString("Kullanıcı Kodu Bos Geçilemez...!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль пользователя неверен....
        /// </summary>
        internal static string Kullanıcı_Şifreniz_Yanlış___ {
            get {
                return ResourceManager.GetString("Kullanıcı Şifreniz Yanlış...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите клиента из списка....
        /// </summary>
        internal static string Listeden_Müşteriyi_Seçiniz___ {
            get {
                return ResourceManager.GetString("Listeden Müşteriyi Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите человека из списка....
        /// </summary>
        internal static string Listeneden_Kişi_Seçiniz___ {
            get {
                return ResourceManager.GetString("Listeneden Kişi Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, свяжитесь со стойкой регистрации....
        /// </summary>
        internal static string Lüften_Resepsiyon_ile_Görüşün___ {
            get {
                return ResourceManager.GetString("Lüften Resepsiyon ile Görüşün...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, выберите подгруппу....
        /// </summary>
        internal static string Lütfen_Alt_Grup_Seçiniz___ {
            get {
                return ResourceManager.GetString("Lütfen Alt Grup Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите основную группу....
        /// </summary>
        internal static string Lütfen_Ana_Grup_Seçiniz___ {
            get {
                return ResourceManager.GetString("Lütfen Ana Grup Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        internal static string Lütfen_Bekleyiniz___ {
            get {
                return ResourceManager.GetString("Lütfen Bekleyiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, закройте счет еще раз....
        /// </summary>
        internal static string Lütfen_Hesabı_Tekrar_Kapatın___ {
            get {
                return ResourceManager.GetString("Lütfen Hesabı Tekrar Kapatın...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, выберите счет....
        /// </summary>
        internal static string Lütfen_Hesap_Seçiniz___ {
            get {
                return ResourceManager.GetString("Lütfen Hesap Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, создайте счет закрытия...
        /// </summary>
        internal static string Lütfen_Kapatma_Hesabı_Tanıtınız__ {
            get {
                return ResourceManager.GetString("Lütfen Kapatma Hesabı Tanıtınız..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, создайте код закрытия...
        /// </summary>
        internal static string Lütfen_Kapatma_Kodu_Tanıtınız__ {
            get {
                return ResourceManager.GetString("Lütfen Kapatma Kodu Tanıtınız..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, создайте PR из кодов пользователей....
        /// </summary>
        internal static string Lütfen_Kullanıcı_Kodlarından_PR_Tanımlayınız___ {
            get {
                return ResourceManager.GetString("Lütfen Kullanıcı Kodlarından PR Tanımlayınız...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, выберите отделение...
        /// </summary>
        internal static string Lütfen_Şube_Seçiniz__ {
            get {
                return ResourceManager.GetString("Lütfen Şube Seçiniz..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почта успешно отправлена..
        /// </summary>
        internal static string Mail_Başarıyla_Gönderildi_ {
            get {
                return ResourceManager.GetString("Mail Başarıyla Gönderildi.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось отправить письмо....
        /// </summary>
        internal static string Mail_Gönderilemedi___ {
            get {
                return ResourceManager.GetString("Mail Gönderilemedi...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о столе не найдена....
        /// </summary>
        internal static string Masa_Bilgisi_Bulunamadı___ {
            get {
                return ResourceManager.GetString("Masa Bilgisi Bulunamadı...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешения на стол открыты...
        /// </summary>
        internal static string Masa_İzinleri_Açıldı__ {
            get {
                return ResourceManager.GetString("Masa İzinleri Açıldı..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер стола не может быть пустым....
        /// </summary>
        internal static string Masa_Numarı_Boş_Geçilemez___ {
            get {
                return ResourceManager.GetString("Masa Numarı Boş Geçilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стол закрыт для продажи....
        /// </summary>
        internal static string Masa_Satışa_Kapalı___ {
            get {
                return ResourceManager.GetString("Masa Satışa Kapalı...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, выберите стол....
        /// </summary>
        internal static string Masa_Seçiniz___ {
            get {
                return ResourceManager.GetString("Masa Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стол.
        /// </summary>
        internal static string Masayı {
            get {
                return ResourceManager.GetString("Masayı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы превысили максимальную сумму....
        /// </summary>
        internal static string Max_Miktarı_Geçtiniz___ {
            get {
                return ResourceManager.GetString("Max Miktarı Geçtiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы превысили максимальную сумму....
        /// </summary>
        internal static string Maximum_Miktarı_Geçtiniz___ {
            get {
                return ResourceManager.GetString("Maximum Miktarı Geçtiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старые данные будут удалены до того, как появится меню. Вы уверены ?.
        /// </summary>
        internal static string Menu_Getirilmeden_Önce_Eski_Veriler_Silinecektir__Emin_misiniz__ {
            get {
                return ResourceManager.GetString("Menu Getirilmeden Önce Eski Veriler Silinecektir. Emin misiniz ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найден открытый чек для текущего выбранного. Хотите продолжить с открытым чеком?.
        /// </summary>
        internal static string Mevcut_Cari_için_Açık_çek_bulunmaktadır__Açık_çek_üzerinde_devam_etmek_istiyor_musunuz_ {
            get {
                return ResourceManager.GetString("Mevcut Cari için Açık çek bulunmaktadır. Açık çek üzerinde devam etmek istiyor mu" +
                        "sunuz?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Quantity....
        /// </summary>
        internal static string Miktar_Giriniz___ {
            get {
                return ResourceManager.GetString("Miktar Giriniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Must Be Greater Than Zero..!.
        /// </summary>
        internal static string Miktar_Sıfırdan_Büyük_Olmalıdır___ {
            get {
                return ResourceManager.GetString("Miktar Sıfırdan Büyük Olmalıdır..!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квитанция для наличного счета сформирована.... Квитанция №:.
        /// </summary>
        internal static string Nakit_Hesaplar_için_Fis_Oluştu_____Fis_No__ {
            get {
                return ResourceManager.GetString("Nakit Hesaplar için Fis Oluştu.... Fis No :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите выписать оборотную ведомость (Mahsup) для наличного счета?.
        /// </summary>
        internal static string Nakit_Hesaplar_için_Mahsup_Kesmek_İstiyor_Musunuz__ {
            get {
                return ResourceManager.GetString("Nakit Hesaplar için Mahsup Kesmek İstiyor Musunuz ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наличные денежные средства обработаны..
        /// </summary>
        internal static string Nakitler_İşlendi_ {
            get {
                return ResourceManager.GetString("Nakitler İşlendi.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс счета NL недостаточен.
        /// </summary>
        internal static string NL_Hesap_Bakiye_Yetersizdir_ {
            get {
                return ResourceManager.GetString("NL Hesap Bakiye Yetersizdir.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс счета NL недостаточен...Оставшийся баланс :.
        /// </summary>
        internal static string NL_Hesap_Bakiye_Yetersizdir__Kalan_Bakiye__ {
            get {
                return ResourceManager.GetString("NL Hesap Bakiye Yetersizdir..Kalan Bakiye :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL стол в настоящее время заполнен. Стол не может быть возвращен....
        /// </summary>
        internal static string NL_Masa_Şuan_Dolu_Masa_Geri_Alınamıyor___ {
            get {
                return ResourceManager.GetString("NL Masa Şuan Dolu Masa Geri Alınamıyor...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № фактуры квитанции изменен....
        /// </summary>
        internal static string Nolu_Fisin_Fatura_Numarası_Değişti___ {
            get {
                return ResourceManager.GetString("Nolu Fisin Fatura Numarası Değişti...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-Out из номера совершен. Регистрация отменена..
        /// </summary>
        internal static string Oda_Check_Out_Olmuştur_Kayıt_İşlemi_İptal_Edilmiştir_ {
            get {
                return ResourceManager.GetString("Oda Check-Out Olmuştur.Kayıt İşlemi İptal Edilmiştir.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комната пуста (not In-House).
        /// </summary>
        internal static string Oda_In_House_Değildir_ {
            get {
                return ResourceManager.GetString("Oda In-House Değildir.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платеж получен, но счет не закрыт....
        /// </summary>
        internal static string Ödeme_Alındı_Fakat_Hesap_Kapanmadı___ {
            get {
                return ResourceManager.GetString("Ödeme Alındı Fakat Hesap Kapanmadı...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код оплаты не может быть пустым....
        /// </summary>
        internal static string Ödeme_Kodu_Boş_Geçilemez___ {
            get {
                return ResourceManager.GetString("Ödeme Kodu Boş Geçilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите строку кода оплаты...
        /// </summary>
        internal static string Ödeme_Kodu_Satırını_Seçiniz__ {
            get {
                return ResourceManager.GetString("Ödeme Kodu Satırını Seçiniz..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Payment Amount....
        /// </summary>
        internal static string Odeme_Tutarını_Giriniz___ {
            get {
                return ResourceManager.GetString("Odeme Tutarını Giriniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте сумму платежа..
        /// </summary>
        internal static string Ödeme_Tutarını_Kontrol_ediniz_ {
            get {
                return ResourceManager.GetString("Ödeme Tutarını Kontrol ediniz.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка в сумме платежа..
        /// </summary>
        internal static string Ödeme_Tutarlarında_Bir_Yanlışlık_Var_ {
            get {
                return ResourceManager.GetString("Ödeme Tutarlarında Bir Yanlışlık Var.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платежи или скидки не могут быть удалены..
        /// </summary>
        internal static string Ödemeler_veya_İndirimler_Silinemez__ {
            get {
                return ResourceManager.GetString("Ödemeler veya İndirimler Silinemez..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя вводить описания по платежам или скидкам...
        /// </summary>
        internal static string Ödemelere_veya_İndirimlere_Açıklama_Girilemez__ {
            get {
                return ResourceManager.GetString("Ödemelere veya İndirimlere Açıklama Girilemez..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На ÖKC не найдено приложение для оплаты чека на питание.
        /// </summary>
        internal static string ÖKC_Üzerinde_Yemek_Ceki_Ödeme_Uygulanaması_Bulunamadı {
            get {
                return ResourceManager.GetString("ÖKC Üzerinde Yemek Ceki Ödeme Uygulanaması Bulunamadı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата работы фронт-офиса и системная дата отличаются..
        /// </summary>
        internal static string Önbüro_Çalışma_Tarihi_ile_Sistem_tarihi_Farklı_ {
            get {
                return ResourceManager.GetString("Önbüro Çalışma Tarihi ile Sistem tarihi Farklı.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата работы фронт-офиса и системная дата отличаются.\nВыйдите  и снова войдите в систему....
        /// </summary>
        internal static string Önbüro_Çalışma_Tarihi_ile_Sistem_tarihi_Farklı_Sistemden_Çıkıp_Yeniden_Giriniz___ {
            get {
                return ResourceManager.GetString("Önbüro Çalışma Tarihi ile Sistem tarihi Farklı.Sistemden Çıkıp Yeniden Giriniz..." +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos Date:.
        /// </summary>
        internal static string PosTar_ {
            get {
                return ResourceManager.GetString("PosTar:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the Program.
        /// </summary>
        internal static string Programı_Kapatıp {
            get {
                return ResourceManager.GetString("Programı Kapatıp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы должны закрыть программу и снова войти в нее....
        /// </summary>
        internal static string Programı_Kapatıp_nYeniden_Programa_Giriş_Yapmanız_Gerekmektedir___ {
            get {
                return ResourceManager.GetString("Programı Kapatıp\\nYeniden Programa Giriş Yapmanız Gerekmektedir...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы должны ввести имя отчета….
        /// </summary>
        internal static string Rapor_Adı_Girmelisiniz___ {
            get {
                return ResourceManager.GetString("Rapor Adı Girmelisiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить отчет в базу данных...?.
        /// </summary>
        internal static string Rapor_Dataya_Kaydedilsin_mi____ {
            get {
                return ResourceManager.GetString("Rapor Dataya Kaydedilsin mi...?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбой в записи отчета. Пожалуйста,попробуйте еще раз....
        /// </summary>
        internal static string Rapor_kayıt_işlemi_basarısız__Lütfen_tekrar_deneyiniz___ {
            get {
                return ResourceManager.GetString("Rapor kayıt işlemi basarısız, Lütfen tekrar deneyiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Purchase Request.
        /// </summary>
        internal static string Remote_Satın_Alma_Talebi {
            get {
                return ResourceManager.GetString("Remote Satın Alma Talebi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Far Stock Count.
        /// </summary>
        internal static string Remote_Stok_Sayım {
            get {
                return ResourceManager.GetString("Remote Stok Sayım", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Product Returns.
        /// </summary>
        internal static string Remote_Urun_Iade {
            get {
                return ResourceManager.GetString("Remote Urun Iade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите удалить бронирование...?.
        /// </summary>
        internal static string Rezervasyon_Silmek_İstiyor_Musunuz____ {
            get {
                return ResourceManager.GetString("Rezervasyon Silmek İstiyor Musunuz...?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadece Genel Çek Raporundan Fişi Detayına Gidebilirsiniz...
        ///59/5000
        ///You can only go to the Voucher Detail from the General Check Report ...
        ///Send feedback
        ///History
        ///Saved
        ///Community.
        /// </summary>
        internal static string Sadece_Genel_Çek_Raporundan_Fişi_Detayına_Gidebilirsiniz___ {
            get {
                return ResourceManager.GetString("Sadece Genel Çek Raporundan Fişi Detayına Gidebilirsiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете перейти к деталям квитанции только из общего отчета о чеке....
        /// </summary>
        internal static string Sadece_Genel_Çek_Raporundan_Fişi_İptal_Edebilirsiniz___ {
            get {
                return ResourceManager.GetString("Sadece Genel Çek Raporundan Fişi İptal Edebilirsiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете вернуть стол только из общего отчета о чеке....
        /// </summary>
        internal static string Sadece_Genel_Çek_Raporundan_Masa_Geri_Alabilirsiniz___ {
            get {
                return ResourceManager.GetString("Sadece Genel Çek Raporundan Masa Geri Alabilirsiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция по продаже состоится..
        /// </summary>
        internal static string Satış_İşlemi_Gerçekleşecektir_ {
            get {
                return ResourceManager.GetString("Satış İşlemi Gerçekleşecektir.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер бланка счет-заказа перед продажей....
        /// </summary>
        internal static string Satış_yapmadan_önce_Adisyon_Numarasını_giriniz___ {
            get {
                return ResourceManager.GetString("Satış yapmadan önce Adisyon Numarasını giriniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный счет закрыт для расходов..
        /// </summary>
        internal static string Seçilen_Hesap_Harcamaya_Kapatılmıştır_ {
            get {
                return ResourceManager.GetString("Seçilen Hesap Harcamaya Kapatılmıştır.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный счет закрыт для расходов.\nОперация по продаже состоится..
        /// </summary>
        internal static string Seçilen_Hesap_Harcamaya_Kapatılmıştır__nSatış_İşlemi_Gerçekleşecektir_ {
            get {
                return ResourceManager.GetString("Seçilen Hesap Harcamaya Kapatılmıştır.\\nSatış İşlemi Gerçekleşecektir.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный счет закрыт..
        /// </summary>
        internal static string Seçilen_Hesap_Kapatılmıştır_ {
            get {
                return ResourceManager.GetString("Seçilen Hesap Kapatılmıştır.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный счет превысил лимитную сумму..
        /// </summary>
        internal static string Seçili_Hesap_Limit_Tutarını_Aşmıştır_ {
            get {
                return ResourceManager.GetString("Seçili Hesap Limit Tutarını Aşmıştır.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить выбранную запись...?.
        /// </summary>
        internal static string Seçili_Kaydı_Silmek_İstediğinize_Emin_misiniz____ {
            get {
                return ResourceManager.GetString("Seçili Kaydı Silmek İstediğinize Emin misiniz...?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить выбранную запись...?.
        /// </summary>
        internal static string Seçili_Kaydı_Zayi_Yapmak_İstediğinize_Emin_Misiniz____ {
            get {
                return ResourceManager.GetString("Seçili Kaydı Zayi Yapmak İstediğinize Emin Misiniz...?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить выбранные столы...?.
        /// </summary>
        internal static string Seçili_Masaları_Silmek_İstediğinize_Emin_Misiniz____ {
            get {
                return ResourceManager.GetString("Seçili Masaları Silmek İstediğinize Emin Misiniz...?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите вернуть выбранные столы?.
        /// </summary>
        internal static string Seçili_Masayı_Geri_Almak_İstiyor_Musunuz_ {
            get {
                return ResourceManager.GetString("Seçili Masayı Geri Almak İstiyor Musunuz?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите запись для удаления....
        /// </summary>
        internal static string Silinecek_Kaydı_Seçiniz___ {
            get {
                return ResourceManager.GetString("Silinecek Kaydı Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить ?.
        /// </summary>
        internal static string Silmek_İstediğinize_Emin_misiniz__ {
            get {
                return ResourceManager.GetString("Silmek İstediğinize Emin misiniz ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить заказ на печать...?.
        /// </summary>
        internal static string Sipariş_Yazıcıya_Gönderilsin_Mi____ {
            get {
                return ResourceManager.GetString("Sipariş Yazıcıya Gönderilsin Mi...?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш заказ отправлен..
        /// </summary>
        internal static string Siparişiniz_Gönderildi_ {
            get {
                return ResourceManager.GetString("Siparişiniz Gönderildi.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Date and Shipment Date Are Not The Same Please Check!!!.
        /// </summary>
        internal static string Sistem_Tarihi_ile_Pos_Tarihi_Aynı_Değil_Kontrol_Ediniz___ {
            get {
                return ResourceManager.GetString("Sistem Tarihi ile Pos Tarihi Aynı Değil Kontrol Ediniz!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйдите и снова войдите в систему....
        /// </summary>
        internal static string Sistemden_Çıkıp_Yeniden_Giriniz___ {
            get {
                return ResourceManager.GetString("Sistemden Çıkıp Yeniden Giriniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Date:.
        /// </summary>
        internal static string SistemTar_ {
            get {
                return ResourceManager.GetString("SistemTar:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конечный продукт нельзя уменьшить....
        /// </summary>
        internal static string Son_Ürün_Eksiltilemez___ {
            get {
                return ResourceManager.GetString("Son Ürün Eksiltilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при передаче в Sql:.
        /// </summary>
        internal static string Sql_e_Aktarim_Yapılırken_Hata_Olustu_ {
            get {
                return ResourceManager.GetString("Sql\'e Aktarim Yapılırken Hata Olustu:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружена ошибка в коде SQL.
        /// </summary>
        internal static string SQL_kodunda_hataya_rastlandı {
            get {
                return ResourceManager.GetString("SQL kodunda hataya rastlandı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Филиал не может быть пустым..
        /// </summary>
        internal static string Sube_Boş_Geçilemez_ {
            get {
                return ResourceManager.GetString("Sube Boş Geçilemez.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите филиал...
        /// </summary>
        internal static string Şube_Seçiniz__ {
            get {
                return ResourceManager.GetString("Şube Seçiniz..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные филиала будут переданы. Вы уверены?.
        /// </summary>
        internal static string Şube_Verileri_Transfer_edilecek__Eminmisiniz_ {
            get {
                return ResourceManager.GetString("Şube Verileri Transfer edilecek. Eminmisiniz?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продажи были переведены из филиала в центр.
        /// </summary>
        internal static string Şubeden___Merkeze_Satışlar_Aktarıldı_ {
            get {
                return ResourceManager.GetString("Şubeden - Merkeze Satışlar Aktarıldı.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле даты не может быть пустым..
        /// </summary>
        internal static string Tarih_Alanı_Boş_Geçilemez_ {
            get {
                return ResourceManager.GetString("Tarih Alanı Boş Geçilemez.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать ежедневную карту Check Out на эту дату?.
        /// </summary>
        internal static string Tarihindeki_Günü_Birlik_Kartlara_Check_Out_Uygulansın_mı__ {
            get {
                return ResourceManager.GetString("Tarihindeki Günü Birlik Kartlara Check Out Uygulansın mı ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать общий возврат дохода на эту дату?.
        /// </summary>
        internal static string Tarihindeki_Toplu_Gelir_İade_Kapatma_Uygulansın_mı__ {
            get {
                return ResourceManager.GetString("Tarihindeki Toplu Gelir İade Kapatma Uygulansın mı ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствуют курсы валют на эту дату...Вы можете определить курс самомтоятельно в окне курса..
        /// </summary>
        internal static string Tarihli_Kurlar_Yoktur_Kur_Girişinden_Günlük_Kurları_Tanımlayabilirisiniz_ {
            get {
                return ResourceManager.GetString("Tarihli Kurlar Yoktur.Kur Girişinden Günlük Kurları Tanımlayabilirisiniz.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применимо к установкам, работающим с бесконтактной картой..
        /// </summary>
        internal static string Temassız_Kartla_Çalışan_Tesisler_İçin_Geçerlidir_ {
            get {
                return ResourceManager.GetString("Temassız Kartla Çalışan Tesisler İçin Geçerlidir.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите физическую фактуру или юридическую фактуру.
        /// </summary>
        internal static string TEMEL_FATURA_veya_TICARI_FATURA_Olarak_Belirtiniz__ {
            get {
                return ResourceManager.GetString("TEMEL FATURA veya TICARI FATURA Olarak Belirtiniz..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправлено тестовое письмо....
        /// </summary>
        internal static string Test_Maili_Gönderildi___ {
            get {
                return ResourceManager.GetString("Test Maili Gönderildi...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее количество людей за столом :.
        /// </summary>
        internal static string Toplam_Masa_Kişi_Sayısı__ {
            get {
                return ResourceManager.GetString("Toplam Masa Kişi Sayısı :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, заполните все поля...!.
        /// </summary>
        internal static string Tüm_Alanları_Doldurunuz____ {
            get {
                return ResourceManager.GetString("Tüm Alanları Doldurunuz...!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Amount....
        /// </summary>
        internal static string Tutar_Giriniz___ {
            get {
                return ResourceManager.GetString("Tutar Giriniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа продуктов не может быть пустой....
        /// </summary>
        internal static string Urun_Grubu_Bos_Geçilemez___ {
            get {
                return ResourceManager.GetString("Urun Grubu Bos Geçilemez...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код продукта не найден....
        /// </summary>
        internal static string Ürün_Kodu_Bulunamadı___ {
            get {
                return ResourceManager.GetString("Ürün Kodu Bulunamadı...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        internal static string Uyarı {
            get {
                return ResourceManager.GetString("Uyarı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните поля «Налоговая инспекция» и «Налоговый номер»..
        /// </summary>
        internal static string Vergi_Daire_ve_Vergi_No_Alanlarını_Doldurunuz__ {
            get {
                return ResourceManager.GetString("Vergi Daire ve Vergi No Alanlarını Doldurunuz..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация будет передана в RMOS ULTIMATE POS \r\n Вы хотите продолжить?.
        /// </summary>
        internal static string Yazarkasa_Eslestirmesiyle_Gelen_Departman_Kısım__VB__Bilgileri_RMOS_ULTIMATE_POS_a_Aktarılacaktır__r_n_Devam_Etmek_Istiyor_musunuz {
            get {
                return ResourceManager.GetString("Yazarkasa Eslestirmesiyle Gelen Departman(Kısım) VB. Bilgileri RMOS ULTIMATE POS\'" +
                        "a Aktarılacaktır \\r\\n Devam Etmek Istiyor musunuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас нет полномочий удалять напечатанные строки...!.
        /// </summary>
        internal static string Yazdırılmış_Satır_Silme_Yetkiniz_Yoktur____ {
            get {
                return ResourceManager.GetString("Yazdırılmış Satır Silme Yetkiniz Yoktur...!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите область для печати....
        /// </summary>
        internal static string Yazılacak_Alanı_Seçiniz___ {
            get {
                return ResourceManager.GetString("Yazılacak Alanı Seçiniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Можно использовать для заказов YemekSepeti..
        /// </summary>
        internal static string YemekSepeti_Siparişleri_için_kullanılabilir_ {
            get {
                return ResourceManager.GetString("YemekSepeti Siparişleri için kullanılabilir.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая дата не может быть больше даты системного сервера!!!!.
        /// </summary>
        internal static string Yeni_tarih_Sistem_Server_tarihinden_Büyük_Olamaz_____nDevam_etmek_İstiyor_Musunuz_ {
            get {
                return ResourceManager.GetString("Yeni tarih Sistem Server tarihinden Büyük Olamaz!!!!\\nDevam etmek İstiyor Musunuz" +
                        "?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to re-enter the program....
        /// </summary>
        internal static string Yeniden_Programa_Giriş_Yapmanız_Gerekmektedir___ {
            get {
                return ResourceManager.GetString("Yeniden Programa Giriş Yapmanız Gerekmektedir...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Operations.
        /// </summary>
        internal static string Yönetim_İşlemleri {
            get {
                return ResourceManager.GetString("Yönetim İşlemleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите сумму для загрузки....
        /// </summary>
        internal static string Yüklenecek_Limit_Tutarını_Giriniz___ {
            get {
                return ResourceManager.GetString("Yüklenecek Limit Tutarını Giriniz...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Yükleniyor___ {
            get {
                return ResourceManager.GetString("Yükleniyor...", resourceCulture);
            }
        }
    }
}
